import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {warmMaterials} from './warm-materials.js';
import {createMissions} from './missions.js';
const $=s=>document.querySelector(s),panel=$('#panel'),dialog=$('#dialog'),dc=$('#dialog-content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial={name:'小林',hair:'#352619',outfit:'#dfd6bd',skin:'#b77e56',hairstyle:2,gender:'female',answers:[],home:0,joined:false,interest:'阅读与手作',tags:'阅读、散步',wish:'和邻居一起读完一本书',coins:150,furniture:'',messages:{},rewards:[],watered:false};
let saved={};try{saved=JSON.parse(localStorage.getItem('senyou-demo-v1')||'{}');}catch{}
const state={...initial,...saved};let page='welcome',town,details,avatar,stageObject,night=false,team=false,walking=false,cameraMove=null,walkTarget=null,growthTween=null,lastTime=0,folded=false,fireflies;
const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dae4cd');scene.fog=new THREE.Fog('#dae4cd',72,150);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,200);camera.position.set(33,29,43);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{$('#load').innerHTML='当前设备无法显示三维画面。请用支持 WebGL 的浏览器打开。<p><a href="assets/hero.jpg">查看小镇全景图</a></p>';throw Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;$('#world').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-1,2,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.475;controls.minDistance=3.5;controls.maxDistance=78;controls.autoRotate=!reduced;controls.autoRotateSpeed=.17;
const hemi=new THREE.HemisphereLight('#fff3df','#c2b68f',3);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0d6',1.65);sun.position.set(-18,28,14);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-27,right:27,top:24,bottom:-24,near:.5,far:90});sun.shadow.bias=-.0006;sun.shadow.normalBias=.04;scene.add(sun);
const fill=new THREE.DirectionalLight('#f6f5e7',1.2);fill.position.set(12,14,-12);scene.add(fill);
const stage=new THREE.Group();stage.visible=false;scene.add(stage);
const houseLocations=[[-7,-4],[2,4],[-8,6],[9,6],[-15,1],[15,0],[-14,10],[0,12],[13,11],[-14,-9],[1,-10],[13,-10]];
const houseNames=['林间书屋','晨光露台','屋顶花园','晚风小舍','树影会客厅','苔庭小屋','远眺阁楼','暖灯工坊','草木露台','听雨木屋','邻里客厅','月光花房'];
const residents=['小林','阿禾','言溪','南川','木木','小岚','清和','向晚','小满','鹿鸣','之遥','知秋'];const hobbies=['阅读与手作','户外与自然'];let teamMembers=[];
const baseLocations=houseLocations.map(p=>[...p]);
function applyDistrict(){if(!town)return;for(let i=0;i<12;i++)houseLocations[i]=[...baseLocations[i]];if(state.joined){const reading=state.interest==='阅读与手作',current=houseLocations[state.home][0]<=0;if(reading!==current){const other=reading?0:3;[houseLocations[state.home],houseLocations[other]]=[houseLocations[other],houseLocations[state.home]];}}for(let i=0;i<12;i++){const o=town.getObjectByName('House_'+String(i).padStart(2,'0'));if(o){o.position.x=houseLocations[i][0];o.position.z=-houseLocations[i][1];}}}
function element(tag,cls,html=''){const e=document.createElement(tag);e.className=cls;e.innerHTML=html;$('#app').appendChild(e);return e;}
const pinLayer=element('div','house-pins'),pins=[],hud=element('div','hud'),fold=element('button','fold-button','收起面板');hud.hidden=fold.hidden=true;
const districtLabels=hobbies.map(t=>{const d=element('div','district-label',t+'街区');d.hidden=true;return d;});
fold.onclick=()=>{folded=!folded;panel.hidden=folded;fold.textContent=folded?'展开面板':'收起面板';};
const stick=element('div','joystick','<button data-key="w" aria-label="向前走">↑</button><button data-key="a" aria-label="向左走">←</button><button data-key="s" aria-label="向后走">↓</button><button data-key="d" aria-label="向右走">→</button>');
const keys={};document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||dialog.open)return;if(['w','a','s','d','ArrowUp','ArrowLeft','ArrowDown','ArrowRight'].includes(e.key)){keys[e.key]=true;if(walking)e.preventDefault();}});document.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));stick.querySelectorAll('button').forEach(b=>{b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;});
function save(){try{localStorage.setItem('senyou-demo-v1',JSON.stringify(state));}catch{}hud.textContent=`◉ ${state.coins} 枚小镇金币`;hud.hidden=!state.joined;}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function focus(pos,target,duration=1500){controls.autoRotate=false;const p=new THREE.Vector3(...pos),t=new THREE.Vector3(...target);if(innerWidth<=640){const offset=p.clone().sub(t).multiplyScalar(stage.visible?1.35:1.5);p.copy(t).add(offset);t.y-=stage.visible?2.4:3.4;}else if(stage.visible){const right=new THREE.Vector3().subVectors(p,t).cross(new THREE.Vector3(0,1,0)).normalize();t.addScaledVector(right,1.7);p.addScaledVector(right,1.7);}cameraMove={from:camera.position.clone(),to:p,tf:controls.target.clone(),tt:t,start:performance.now(),duration:reduced?1:duration};}
function locationLabel(title,sub){$('#location').innerHTML=`<span class="location-dot"></span><div>${esc(title)}<small>${esc(sub)}</small></div>`;}
function modal(html){dc.innerHTML=html;if(!dialog.open)dialog.showModal();}
$('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function card(html){panel.className='panel card';panel.hidden=false;panel.innerHTML=html;panel.scrollTop=0;fold.hidden=false;folded=false;fold.textContent='收起面板';}
function btn(id,fn){const b=$('#'+id);if(b)b.onclick=fn;}
function ready(){if(!town||!details){toast('小镇还在准备，请稍等片刻。');return false;}return true;}
function award(key,n){if(!state.rewards.includes(key)){state.rewards.push(key);state.coins+=n;save();toast(`获得 ${n} 枚金币，可以继续布置自己的树屋。`);}}
function clearStage(){stage.clear();stageObject=null;stage.visible=false;if(town)town.visible=true;pinLayer.hidden=false;}
function showStage(name,scale=1){clearStage();town.visible=false;pinLayer.hidden=true;stage.visible=true;walking=false;stick.classList.remove('visible');stageObject=details.getObjectByName(name)?.clone(true);if(stageObject){stageObject.position.set(0,0,0);stageObject.rotation.set(0,0,0);stageObject.scale.setScalar(scale);stage.add(stageObject);}return stageObject;}
function cloneMats(o){o.traverse(n=>{if(n.isMesh){const source=n.material;n.material=source.clone();n.material.onBeforeCompile=source.onBeforeCompile;n.material.customProgramCacheKey=source.customProgramCacheKey;}});}
function styleAvatar(obj){obj?.traverse(o=>{if(o.name.startsWith('Body_'))o.visible=o.name==='Body_'+state.gender;if(/^Hair_[0-3]$/.test(o.name))o.visible=o.name==='Hair_'+state.hairstyle;if(!o.isMesh)return;const n=o.material.name;if(n==='avatar_outfit')o.material.color.set(state.outfit);if(n==='avatar_skin')o.material.color.set(state.skin);if(n==='avatar_hair')o.material.color.set(state.hair);});}
function capturePortrait(){const r=new THREE.WebGLRenderer({antialias:true});r.setSize(300,300);r.toneMapping=THREE.ACESFilmicToneMapping;const c=new THREE.PerspectiveCamera(34,1,.1,100);c.position.set(2.5,2.6,6.5);c.lookAt(0,2,0);r.render(scene,c);state.portrait=r.domElement.toDataURL('image/jpeg',.85);r.dispose();}
const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath('./vendor/draco/');loader.setDRACOLoader(draco);
Promise.all([loader.loadAsync('./assets/town-optimized.glb',p=>{$('#load progress').value=p.total?p.loaded/p.total*75:25;}),loader.loadAsync('./assets/details-optimized.glb'),loader.loadAsync('./assets/resident-v2.glb')]).then(([g,h,a])=>{
 town=g.scene;details=h.scene;details.getObjectByName('AvatarStudio')?.removeFromParent();details.add(a.scene.getObjectByName('AvatarStudio'));scene.add(town);applyDistrict();town.traverse(o=>{if(o.isMesh){o.castShadow=!/leaf/.test(o.name);o.receiveShadow=true;const m=o.material;if(/leaf/.test(o.name)){m.side=THREE.DoubleSide;m.color.set(['#4e6538','#637749','#738259','#80906b','#566e43','#86936b','#49644a'][Number(m.name.slice(-1))||0]);m.roughness=.95;}if(m.name==='grass'){m.color.set('#727e4f');m.roughness=1;}if(m.name==='bark'){m.map=null;m.color.set('#64513a');m.roughness=1;}if(m.name==='stone'){m.color.set('#b7ac90');m.map=null;}if(m.name==='earth'){m.color.set('#63523c');m.map=null;}}});
 warmMaterials(town);warmMaterials(details);
 town.getObjectByName('Avatar').visible=false;avatar=details.getObjectByName('AvatarStudio').clone(true);cloneMats(avatar);styleAvatar(avatar);avatar.position.set(0,.43,6.2);town.add(avatar);
 for(let i=0;i<12;i++){let b=document.createElement('button');b.className='house-pin';b.textContent=houseNames[i];b.setAttribute('aria-label','拜访'+houseNames[i]);b.onclick=()=>visit(i);pinLayer.appendChild(b);pins.push({el:b,index:i});}
 const geom=new THREE.BufferGeometry(),pts=[];for(let i=0;i<95;i++)pts.push((Math.random()-.5)*40,Math.random()*5+1,(Math.random()-.5)*30);geom.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));fireflies=new THREE.Points(geom,new THREE.PointsMaterial({color:'#ffd484',size:.065,transparent:true,opacity:.85}));fireflies.visible=false;scene.add(fireflies);
 $('#load').classList.add('hidden');window.__senyouReady=true;save();if(state.joined)$('#start').innerHTML='回到我的树屋 <span>↗</span>';
}).catch(e=>{console.error(e);$('#load').innerHTML='小镇暂时没能载入。<button id="retry">重新载入</button>';btn('retry',()=>location.reload());});
function setNight(value){night=value;document.body.classList.toggle('night',night);$('#day').textContent=night?'☾ 夜晚':'☼ 白昼';$('#day').setAttribute('aria-pressed',night);sun.intensity=night?.55:1.65;hemi.intensity=night?1.25:3;fill.intensity=night?.8:1.2;scene.background.set(night?'#52665c':'#dae4cd');scene.fog.color.copy(scene.background);renderer.toneMappingExposure=night?1.2:1.02;if(fireflies)fireflies.visible=night;town?.traverse(o=>{if(o.isMesh&&/warmglass| light/.test(o.name))o.material.emissiveIntensity=night?2.5:.15;});}
$('#day').onclick=()=>setNight(!night);
let audioContext,audioGain;$('#sound').onclick=()=>{if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();audioGain=audioContext.createGain();audioGain.gain.value=0;audioGain.connect(audioContext.destination);const buffer=audioContext.createBuffer(1,audioContext.sampleRate*4,audioContext.sampleRate),a=buffer.getChannelData(0);let last=0;for(let i=0;i<a.length;i++){last=(last+(Math.random()*2-1)*.018)/1.018;a[i]=last*2;}const n=audioContext.createBufferSource();n.buffer=buffer;n.loop=true;const f=audioContext.createBiquadFilter();f.type='lowpass';f.frequency.value=700;n.connect(f);f.connect(audioGain);n.start();}audioContext.resume();const on=$('#sound').getAttribute('aria-pressed')!=='true';$('#sound').setAttribute('aria-pressed',on);$('#sound').setAttribute('aria-label',on?'关闭自然声音':'开启自然声音');audioGain.gain.setTargetAtTime(on?.20:0,audioContext.currentTime,.4);toast(on?'林间风声已开启':'声音已关闭');};
function begin(edit=false){if(!ready())return;if(state.joined&&!edit){home();return;}page='avatar';const a=showStage('AvatarStudio',2.1);cloneMats(a);styleAvatar(a);focus(innerWidth<=640?[6,4.8,10]:[4.4,3.5,7],[0,innerWidth<=640?1.6:1.8,0]);locationLabel('新居民登记','先捏一个自己，再去领取种子');
 card(`<p class="eyebrow">01 / MAKE YOURSELF AT HOME</p><h2>先认识一下你</h2><label for="nickname">小镇昵称</label><input id="nickname" maxlength="12" value="${esc(state.name)}"><label>性别外观</label><div class="option-row">${[['female','女性'],['male','男性'],['neutral','中性']].map(([v,t])=>`<button class="choice ${state.gender===v?'selected':''}" data-gender="${v}" aria-pressed="${state.gender===v}">${t}</button>`).join('')}</div><p class="meta">选择舒服的外观。所有发型与穿搭都可以自由搭配。</p><label>日常穿搭</label><div class="option-row">${['#dfd6bd','#7f9277','#b58a64','#546b75'].map(c=>`<button class="swatch ${state.outfit===c?'selected':''}" data-outfit="${c}" style="background:${c}" aria-label="衣服颜色 ${c}"></button>`).join('')}</div><label>发型</label><div class="option-row">${['利落短发','自然蓬松','齐耳短发','低马尾'].map((x,i)=>`<button class="choice ${state.hairstyle===i?'selected':''}" data-hair="${i}">${x}</button>`).join('')}</div><label>发色与肤色</label><div class="option-row">${['#352619','#755038','#a88051'].map(c=>`<button class="swatch" data-haircolor="${c}" style="background:${c}" aria-label="发色 ${c}"></button>`).join('')}<span style="width:12px"></span>${['#b77e56','#e0b994','#82563f'].map(c=>`<button class="swatch" data-skin="${c}" style="background:${c}" aria-label="肤色 ${c}"></button>`).join('')}</div><button id="avatar-next" class="primary dark">${edit?'保存我的新造型':'就这样，领取种子'} <span>→</span></button><p class="tiny-note">形象与昵称仅保存在这台设备的演示中。</p>`);
 panel.classList.add('avatar-panel');panel.querySelectorAll('[data-outfit],[data-hair],[data-haircolor],[data-skin],[data-gender]').forEach(b=>b.onclick=()=>{for(const[k,v]of Object.entries(b.dataset)){const field={outfit:'outfit',hair:'hairstyle',haircolor:'hair',skin:'skin',gender:'gender'}[k];state[field]=k==='hair'?Number(v):v;panel.querySelectorAll('[data-'+k+']').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b);});}styleAvatar(a);styleAvatar(avatar);save();});btn('avatar-next',()=>{state.name=$('#nickname').value.trim()||'新邻居';capturePortrait();save();if(edit)home();else seed();});}
const questions=[{q:'开始一件新事情时，你通常会先……',a:['先行动，在尝试中调整','和别人聊聊，激发灵感','了解伙伴的节奏与需要','把资料和细节弄清楚']},{q:'面对一个临时任务，你更愿意……',a:['提出目标，推动进展','找人一起，把气氛带起来','协调分工，让每个人安心','梳理要求，检查遗漏']},{q:'当意见不一致时，你希望……',a:['尽快做出决定','把想法开诚布公地说出来','给彼此多一点时间','先把依据与逻辑讲清楚']},{q:'来到新环境，你通常会……',a:['主动试一试新的机会','认识不同的人','先熟悉身边的小圈子','观察规则，了解运作方式']},{q:'和你一起工作时，什么更重要？',a:['目标明确，沟通直接','表达自由，及时回应','安排稳定，互相支持','信息完整，质量可靠']},{q:'任务完成以后，你最想……',a:['看看下一件值得挑战的事','和伙伴分享喜悦','感谢一起投入的人','回顾结果，整理改进的方法']}];
function seed(){page='seed';showStage('Seed');focus([3.7,2.7,4.7],[0,.1,0]);locationLabel('一颗还没有名字的种子','关于自己的回答，会让它慢慢长大');card(`<p class="eyebrow">02 / A SMALL BEGINNING</p><h2>${esc(state.name)}，<br>这是你的种子。</h2><p>现在还不知道，它会长成什么样子。</p><p>接下来，每回答一组关于自己的问题，你都能看见一点新的生长。</p><button id="seed-next" class="primary dark">开始陪它长大 <span>→</span></button><p class="tiny-note">这里使用 6 道体验示例题，并非正式 DISC 题库，不输出心理测评结论。</p>`);btn('seed-next',()=>{state.answers=[];question();});}
function showGrowth(n){if(n<4){showStage(['Seed','Sprout','Sapling','Canopy'][n]);focus(n<2?[3.5,2.7,4.8]:[6,4.8,7],[0,n<2?.3:1.4,0],750);}else{clearStage();town.visible=false;pinLayer.hidden=true;stage.visible=true;const h=town.getObjectByName('House_00').clone(true);h.position.set(0,0,0);h.rotation.set(0,0,0);h.traverse(o=>{if(o.isMesh&&n===4&&/shingle|warmglass| light|chimney/.test(o.name))o.visible=false;});stage.add(h);stageObject=h;focus([9,7,12],[0,2.7,0],800);}growthTween={start:performance.now(),obj:stageObject};}
function question(){const n=state.answers.length;if(n>=questions.length){state.home=(state.answers.reduce((a,b)=>a+b,0)+state.answers[0]*3)%12;save();reveal();return;}page='question';showGrowth(n);const q=questions[n];locationLabel(['领取种子','嫩芽破土','树苗舒展','树冠展开','平台搭建','点亮门灯'][n],`第 ${n+1} / 6 组 · 体验示例`);card(`<p class="eyebrow">03 / GROW AT YOUR OWN PACE</p><h2>${['一点点认识自己','第一片新叶','长出自己的节奏','让枝叶舒展','小屋正在搭建','准备点亮新家'][n]}</h2><div class="step-dots">${questions.map((_,i)=>`<span class="${i<n?'done':''}"></span>`).join('')}</div><p class="meta">体验示例 ${n+1} / 6</p><p style="font-size:17px;margin:18px 0">${q.q}</p><div class="answers">${q.a.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('')}</div><p class="tiny-note">按此刻最接近自己的感觉选择。正式版保留原专业题干、选项与计分。</p>`);panel.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.answers.push(Number(b.dataset.answer));save();question();});}
function reveal(){page='reveal';clearStage();town.visible=false;pinLayer.hidden=true;stage.visible=true;const h=town.getObjectByName('House_'+String(state.home).padStart(2,'0')).clone(true);h.position.set(0,0,0);h.rotation.set(0,0,0);stage.add(h);stageObject=h;growthTween={start:performance.now(),obj:h};focus([9,7,12],[0,2.8,0]);locationLabel('树屋落成','名字挂上门牌，这里就有了你的地址');card(`<p class="eyebrow">04 / YOUR FIRST HOME</p><h2>${esc(state.name)}，<br>欢迎回家。</h2><p>${houseNames[state.home]}已经为你亮起灯。</p><div class="resident-number">T${String(state.home+1).padStart(2,'0')} · 037</div><p class="meta">建筑原型编号 · 示例门牌</p><p>每一间树屋，都有自己的节奏。入住之后，家具与庭院由你决定。</p><button id="get-card" class="primary dark">领取我的居民卡 <span>→</span></button><p class="tiny-note">建筑编号与匹配规则为视觉演示；十二类正式 DISC 映射待专业资料接入。</p>`);btn('get-card',()=>{state.joined=true;award('joined',50);save();residentCard(true);});}
function residentCard(edit=false){page='card';focusHome();card(`<p class="eyebrow">05 / RESIDENT CARD</p><div class="resident-header"><h2>${esc(state.name)}</h2><span class="resident-number">T${String(state.home+1).padStart(2,'0')}-037</span></div><p class="meta">${houseNames[state.home]} · ${esc(state.interest)}</p><img src="${state.portrait||'assets/avatar.jpg'}" class="portrait" alt="居民虚拟形象参考"><label for="tags">我的标签</label><input id="tags" maxlength="40" value="${esc(state.tags)}"><label for="wish">我想做的事</label><input id="wish" maxlength="80" value="${esc(state.wish)}"><div class="result-note">我的协作说明书<br><span class="meta">专业报告区域预留。本轮展示居民资料与自我表达。</span></div><button id="card-save" class="primary dark">${edit?'选择兴趣街区':'保存居民卡'} <span>→</span></button><p class="tiny-note">你补充的内容可以继续修改。</p>`);const experience=document.createElement('button');experience.className='secondary';experience.textContent='查看我在协作中留下的经验';experience.onclick=()=>missions.manual();panel.appendChild(experience);btn('card-save',()=>{state.tags=$('#tags').value.trim();state.wish=$('#wish').value.trim();save();if(edit)chooseDistrict();else{toast('居民卡已保存到本机演示。');home();}});}
function chooseDistrict(){page='district';clearStage();focus([31,26,37],[0,2,0]);locationLabel('选择兴趣街区','想做相似事情的人，住得近一点');card(`<p class="eyebrow">06 / FIND YOUR NEIGHBORHOOD</p><h2>想住在哪里？</h2><p>地址跟着兴趣走。你的工作伙伴，可以在团队地图里找到。</p><div class="answers"><button data-district="阅读与手作"><strong>阅读与手作</strong><br>带一本书，分享一个亲手做的东西。</button><button data-district="户外与自然"><strong>户外与自然</strong><br>散步、露营，在草木之间慢慢认识。</button></div><p class="tiny-note">首版呈现两个示意街区。居民昵称与兴趣资料均为演示。</p>`);panel.querySelectorAll('[data-district]').forEach(b=>b.onclick=()=>{state.interest=b.dataset.district;applyDistrict();award('district',20);save();home();toast('已入住'+state.interest+'街区');});}
function focusHouse(index){clearStage();town.visible=false;pinLayer.hidden=true;stage.visible=true;const h=town.getObjectByName('House_'+String(index).padStart(2,'0')).clone(true);h.position.set(0,0,0);h.rotation.set(0,0,0);stage.add(h);stageObject=h;const ground=new THREE.Mesh(new THREE.CylinderGeometry(4.9,5.1,.26,64),new THREE.MeshStandardMaterial({color:'#a5b77e',roughness:1}));ground.position.y=-.2;ground.receiveShadow=true;stage.add(ground);focus([10,8,14],[0,2.8,0]);}
function focusHome(){focusHouse(state.home);}
function home(){if(!ready())return;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='home'));if(!state.joined){begin();return;}page='home';walking=false;stick.classList.remove('visible');focusHome();locationLabel(houseNames[state.home],`${state.interest} · ${state.name}的家`);updatePins();const active=missions.current();card(`<p class="eyebrow">HOME / ${esc(state.interest)}</p><h2>${esc(state.name)}的树屋</h2><p>树屋是你的出发点。带上一个想法，去找到愿意一起把它做成的人。</p><div class="mission-progress"><b>${active?esc(active.title):'第一份使命：和同伴做成一件小事'}</b><span>${active?'看看你的搭子、分工与行动进度':'从一次共读、一场运动，或你自己的点子开始。'}</span></div><button id="home-mission" class="primary dark">${active?'继续这件事':'发起一件想做的事'} →</button><button id="home-board" class="secondary">去广场认领一件事</button><button id="decorate" class="secondary">进屋布置家具</button><button id="edit-look" class="secondary">重新捏自己的造型</button><button id="edit-card" class="text-button">居民卡与协作经验 →</button><button id="neighbor" class="text-button">去拜访一位邻居 →</button><button id="walk" class="text-button">沿着小路走一走 →</button><p class="tiny-note">装扮与进度保存在当前设备。示例居民不会收到真实通知。</p>`);btn('home-mission',()=>active?missions.openCurrent():missions.create());btn('home-board',()=>missions.board());btn('edit-look',()=>begin(true));btn('decorate',decorate);btn('edit-card',()=>residentCard(false));btn('neighbor',()=>visit((state.home+1)%12));btn('walk',explore);}
function decorate(){page='decorate';showStage('Room');focus([9,7,11],[0,1,0]);locationLabel('树屋室内','木地板、书架、茶几，还有你自己的选择');function place(kind){let old=stage.getObjectByName('AddedChair');if(old)stage.remove(old);if(!kind)return;const c=details.getObjectByName('Armchair').clone(true);c.name='AddedChair';cloneMats(c);c.position.set(kind==='窗边休闲椅'?1.6:1.8,.12,kind==='窗边休闲椅'?-1.4:1.5);c.rotation.y=kind==='窗边休闲椅'?-1.1:.6;if(kind==='苔绿阅读椅')c.traverse(o=>{if(o.isMesh&&/terra/.test(o.name))o.material.color.set('#637653');});stage.add(c);}place(state.furniture);
card(`<p class="eyebrow">07 / MAKE IT YOURS</p><h2>添一把喜欢的椅子。</h2><p>选好后，你会在房间里直接看到它。</p><p id="decor-coins">可用金币 <b>${state.coins}</b></p><div class="answers"><button data-chair="窗边休闲椅">窗边休闲椅 · 30 金币<br><span class="meta">陶土色软垫，放在窗旁</span></button><button data-chair="苔绿阅读椅">苔绿阅读椅 · 30 金币<br><span class="meta">草木色软垫，留一个阅读角</span></button></div><p id="decor-status" class="review-status">${state.furniture?'已放置 '+esc(state.furniture):'先选一款，在房间里看看。'}</p><button id="decor-done" class="primary dark">布置好了，去看邻居 <span>→</span></button><button id="decor-home" class="text-button">返回树屋门口</button>`);panel.querySelectorAll('[data-chair]').forEach(b=>b.onclick=()=>{const cost=state.furniture?0:30;if(state.coins<cost){toast('金币还不够，去公园参与一次共建吧。');return;}state.coins-=cost;state.furniture=b.dataset.chair;place(state.furniture);save();$('#decor-status').textContent='已放置 '+state.furniture+(cost?' · 消耗30金币':' · 本轮可免费换款');$('#decor-coins').textContent='可用金币 '+state.coins;toast('新椅子已经放进房间。');});btn('decor-done',()=>visit((state.home+1)%12));btn('decor-home',home);}
function visit(i){if(!ready())return;if(state.joined&&i===state.home){home();return;}clearStage();page='neighbor';walking=false;stick.classList.remove('visible');focusHouse(i);locationLabel(houseNames[i],residents[i]+'的树屋 · 示例居民');card(`<p class="eyebrow">08 / HELLO, NEIGHBOR</p><div class="resident-header"><h2>${residents[i]}</h2><span class="resident-number">T${String(i+1).padStart(2,'0')}-0${21+i}</span></div><p class="meta">${houseNames[i]} · ${hobbies[i%2]}</p><div><span class="tag">${i%2?'徒步':'阅读'}</span><span class="tag">${i%3?'咖啡':'手作'}</span><span class="tag">喜欢慢慢熟悉</span></div><div class="result-note">想做的事<br>${i%2?'周末去附近的山里，走一段不用赶时间的路。':'找几位邻居，交换最近读到的一句话。'}</div><p>屋外留言<br>“${i%2?'如果你也喜欢晚风，欢迎来坐坐。':'最近在读一本很慢的书，欢迎敲门。'}”</p><button id="pair" class="primary dark">悄悄合拍一下 <span>↗</span></button><button id="knock" class="secondary">敲门，留下一句话</button><button id="next-neighbor" class="text-button">去下一位邻居家 →</button><p class="tiny-note">虚构居民与演示资料。合拍仅在本机展示，不通知对方。</p>`);btn('pair',()=>pair(i));btn('knock',()=>knock(i));btn('next-neighbor',()=>visit((i+1)%12));const action=document.createElement('button');action.className='primary dark';action.id='neighbor-mission';action.textContent='从一件想做的事开始合作';panel.insertBefore(action,panel.querySelector('#pair'));action.onclick=()=>missions.board(i%2?'运动与户外':'阅读与交流');}
function pair(i){const lines=[['你可能更习惯先往前推进','可以先约好目标，再留一次彼此校准的时间。'],['你可能更习惯通过交流寻找灵感','聊完想法后，把下一步写成一份短约定。'],['你可能更关注伙伴的感受与节奏','把各自需要的时间说清楚，让配合更安心。'],['你可能更喜欢先把信息想清楚','提前交换背景与标准，也给试验留一点空间。']][state.answers[0]??3];modal(`<p class="eyebrow">PRIVATE / 仅你可见</p><h2>${esc(state.name)} × ${residents[i]}</h2><p class="meta">合拍报告 · 交互示例</p><div class="small-rule"></div><h3 style="font-size:17px">从一件小事开始合作</h3><p>${lines[0]}。${residents[i]}的示例居民卡里，表达了对${i%2?'户外探索':'安静阅读'}的兴趣。</p><div class="result-note">${lines[1]}</div><p>可以先约一次${i%2?'散步，轮流介绍自己喜欢的路线':'共读，各自带来一段喜欢的文字'}，看看彼此舒服的沟通方式。</p><p class="meta">此处为预写协作提示示例，不是专业 DISC 合拍结论。正式报告由蚂蚁提供的专业能力生成。</p><button id="pair-knock" class="primary dark">带一句话去敲门 →</button>`);btn('pair-knock',()=>{dialog.close();knock(i);});}
function knock(i){modal(`<p class="eyebrow">LEAVE A LITTLE HELLO</p><h2>给${residents[i]}留句话</h2><p>留言后，才算完成一次敲门。</p><label for="message">你的留言</label><textarea id="message" rows="3" maxlength="160" placeholder="看到你也喜欢……"></textarea><div class="option-row" style="margin:12px 0"><button class="choice" id="prompt-msg">帮我开个头</button></div><button id="send-msg" class="primary dark">留下这句话，敲敲门</button><p class="meta">本次留言只保存在你的设备，不会发给真实员工。</p><div id="messages">${(state.messages[i]||[]).map(m=>`<div class="message"><small>${esc(state.name)} · 本机留言</small>${esc(m)}</div>`).join('')}</div>`);btn('prompt-msg',()=>$('#message').value=`看到你也喜欢${i%2?'散步':'阅读'}，想来打个招呼。有空一起${i%2?'去公园走走':'交换一本喜欢的书'}吧。`);btn('send-msg',()=>{const m=$('#message').value.trim();if(!m){toast('先写一句话，再敲门吧。');$('#message').focus();return;}state.messages[i]=[...(state.messages[i]||[]),m].slice(-10);save();dialog.close();toast('敲门完成，留言已留在本机的邻居留言板。');});}
function explore(){if(!ready())return;clearStage();page='explore';panel.hidden=true;fold.hidden=false;folded=true;fold.textContent='展开面板';walking=true;stick.classList.add('visible');focus([avatar.position.x+5,6,avatar.position.z+9],[avatar.position.x,1,avatar.position.z]);locationLabel('沿街散步','WASD / 方向键移动 · 点击树屋拜访');toast('方向键可以走动，拖动可以环顾小镇。');}
function publicSpace(kind){if(!ready())return;if(kind==='plaza'){missions.board();return;}clearStage();walking=false;stick.classList.remove('visible');page=kind;focus([10,12,10],[8.5,.5,13.5]);locationLabel('湖畔公园','不必约好时间，也能留下一点连接');card(`<p class="eyebrow">PARK / 留一点时间给偶遇</p><h2>在公园，慢下来。</h2><p>桥边有棋桌，树荫下有长椅。你也可以替还没上线的邻居照顾一盆植物。</p><button id="water" class="primary dark">${state.watered?'看看共同养的小植物':'给共养植物浇一次水'} <span>↗</span></button><button id="park-ideas" class="secondary">看看公园还能怎么玩</button><button id="park-walk" class="text-button">沿着湖边散步 →</button><p class="tiny-note">共养为本机体验。多人小游戏以场景与玩法示意呈现。</p>`);btn('water',()=>{state.watered=true;award('water',20);save();showStage('Sapling');focus([4,3.3,6],[0,1,0]);toast('你照顾过的小树又长大了一点。');$('#water').textContent='今天已经照顾过它了';});btn('park-ideas',()=>modal('<h2>让相遇发生得轻一点</h2><img class="dialog-image" src="assets/park.jpg" alt="湖畔公园与木桥"><p><b>同时在线</b> · 棋桌、跷跷板、划船、双人话题卡。短回合，低压力。</p><p><b>不同时在线</b> · 轮流浇水、漂流瓶、接力涂鸦、帮邻居点亮门灯。</p><p class="meta">这些多人玩法本轮为概念展示。</p>'));btn('park-walk',explore);const action=document.createElement('button');action.className='primary dark';action.id='park-mission';action.textContent='湖畔集合：看看大家想一起做什么';panel.insertBefore(action,panel.querySelector('#water'));action.onclick=()=>missions.board('全部','park');}
function teamView(selected){if(!ready())return;const p=selected||missions.current();clearStage();walking=false;stick.classList.remove('visible');page='team';team=true;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='team'));const members=p?missions.members(p):[];teamMembers=members.map(m=>m.house).filter(Number.isInteger);focus([0,40,29],[0,1,0]);locationLabel('小队地图',p?p.title:'先从一件想做的事，找到彼此');card(`<p class="eyebrow">小队地图 / 因为一件事，走到一起</p><h2>${p?esc(p.title):'搭子不是随机配出来的。'}</h2><p>${p?'每一处亮起的树屋，都是这件事已经确认的参与者。':'先发起或认领一件事，地图会亮起参与者的树屋。'}</p>${members.map(m=>`<button class="secondary" data-team-house="${m.house}">${esc(m.name)} · ${esc(m.role)}</button><p class="meta">${esc(m.pace)}</p>`).join('')}<button id="team-mission" class="primary dark">${p?'回到这件事，看看分工':'去广场找到一件事'}</button><p class="tiny-note">示例小队，只显示已接受邀请或已认领的居民；待回应邀请不会亮起。</p>`);btn('team-mission',()=>p?missions.detail(p.id):missions.board());panel.querySelectorAll('[data-team-house]').forEach(b=>b.onclick=()=>visit(Number(b.dataset.teamHouse)));updatePins();}
function updatePins(){pins.forEach(p=>{p.el.textContent=p.index===state.home&&state.joined?'我的树屋':(team&&teamMembers.includes(p.index)?residents[p.index]+' · 团队成员':houseNames[p.index]);p.el.classList.toggle('team',team&&teamMembers.includes(p.index));});}
function gallery(){const shots=[['hero','小镇全景'],['home','树屋近景'],['interior','树屋室内'],['plaza','中央广场'],['park','湖畔公园'],['lake','林间木桥'],['street','林间街道'],['growth','种子生长'],['twelve-houses','十二间树屋'],['night','夜晚灯光']];modal(`<h2>森友小镇 · 场景图册</h2><p class="meta">同一套 Blender 场景的实景渲染</p><div class="gallery-grid">${shots.map(([k,t])=>`<button data-shot="${k}" aria-label="放大${t}"><img src="assets/${k}.jpg" alt="${t}"><span>${t}</span></button>`).join('')}</div><a href="assets/senyou-visual-proposal.pdf" class="inline-link" target="_blank" rel="noopener">打开完整 PDF 视觉方案书 ↗</a>`);dc.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{modal(`<img class="dialog-image" src="assets/${b.dataset.shot}.jpg" alt="小镇场景大图"><button id="back-gallery" class="secondary">返回图册</button>`);btn('back-gallery',gallery);});}
function navTo(view){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));team=false;updatePins();if(view==='home')home();if(view==='plaza'||view==='park')publicSpace(view);if(view==='team')teamView();if(view==='overview'){if(!ready())return;clearStage();page='overview';walking=false;stick.classList.remove('visible');panel.hidden=true;fold.hidden=true;focus([33,29,43],[-1,2,0]);locationLabel('森林全景','十二间树屋 · 阅读与手作 / 户外与自然两个街区');}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navTo(b.dataset.view));$('#start').onclick=()=>begin();$('#explore').onclick=explore;
$('#guide-button').onclick=()=>{modal('<h2>在小镇走一走</h2><p>拖动鼠标旋转视角，滚轮拉近或拉远。手机可以单指旋转、双指缩放。</p><p>点击树屋门牌可以拜访邻居。散步模式使用 WASD、方向键或屏幕方向按钮移动人物。</p><p>第一次体验可以从领取种子开始；顶部切换昼夜，底部前往广场、公园与想法广场与小队地图。</p><div class="small-rule"></div><p class="meta">这是可交互概念 Demo。题目、居民、报告为演示内容；昵称、留言与装扮仅存于本机。完整多人互动、正式 DISC 与员工系统尚未接入。</p><button id="help-gallery" class="secondary">打开视觉图册</button><button id="restart" class="text-button">重新体验入住流程</button>');btn('help-gallery',gallery);btn('restart',()=>{dialog.close();state.joined=false;state.answers=[];save();begin();});};
const raycaster=new THREE.Raycaster();let pointerStart;renderer.domElement.addEventListener('pointerdown',e=>pointerStart=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>6||!town?.visible)return;raycaster.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=raycaster.intersectObject(town,true)[0];if(hit){let o=hit.object;while(o&&!/^House_\d\d$/.test(o.name))o=o.parent;if(o){visit(Number(o.name.slice(-2)));return;}if(walking){walkTarget=hit.point.clone();walkTarget.y=.43;}}});
function moveAvatar(dt,time){if(!walking||!avatar)return;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dz=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);let v=new THREE.Vector3(dx,0,dz);if(v.length()){walkTarget=null;v.normalize();}else if(walkTarget){v.subVectors(walkTarget,avatar.position);v.y=0;if(v.length()<.1){walkTarget=null;return;}v.normalize();}else return;let next=avatar.position.clone().addScaledVector(v,dt*3.1);if(Math.abs(next.x)>20||Math.abs(next.z)>16)return;for(let[x,y]of houseLocations)if(Math.abs(next.x-x)<1.8&&Math.abs(next.z+y)<1.8)return;if(((next.x-8.1)/3.35)**2+((next.z-8)/2.15)**2<1&&Math.abs(next.z-6.8)>.7)return;const delta=next.clone().sub(avatar.position);avatar.position.copy(next);avatar.position.y=.43+Math.abs(Math.sin(time*8))*.04;avatar.rotation.y=Math.atan2(-v.x,-v.z);if(!cameraMove){camera.position.add(delta);controls.target.add(delta);}}
let elapsed=0;function animate(t){requestAnimationFrame(animate);const dt=Math.min(.04,(t-lastTime)/1000||.016);lastTime=t;elapsed+=dt;if(cameraMove){let q=Math.min(1,(t-cameraMove.start)/cameraMove.duration),e=q*q*(3-2*q);camera.position.lerpVectors(cameraMove.from,cameraMove.to,e);controls.target.lerpVectors(cameraMove.tf,cameraMove.tt,e);if(q===1)cameraMove=null;}if(growthTween){let q=Math.min(1,(t-growthTween.start)/(reduced?1:900));growthTween.obj.scale.setScalar(.88+.12*(1-(1-q)**3));if(q===1)growthTween=null;}moveAvatar(dt,elapsed);if(fireflies&&night&&!reduced){fireflies.rotation.y=Math.sin(elapsed*.07)*.04;fireflies.position.y=Math.sin(elapsed*.7)*.09;}controls.update();pins.forEach(p=>{const[x,y]=houseLocations[p.index],v=new THREE.Vector3(x,4.7,-y).project(camera);p.el.style.left=(v.x*.5+.5)*innerWidth+'px';p.el.style.top=(-v.y*.5+.5)*innerHeight+'px';p.el.hidden=v.z>1||v.x<-.95||v.x>.95||v.y<-.86||v.y>.86||(team&&!teamMembers.includes(p.index))||page==='welcome';});districtLabels.forEach((d,i)=>{const v=new THREE.Vector3(i?10:-10,6.5,-4).project(camera);d.style.left=(v.x*.5+.5)*innerWidth+'px';d.style.top=(-v.y*.5+.5)*innerHeight+'px';d.hidden=!town?.visible||!['overview','district','team'].includes(page)||v.z>1;});renderer.render(scene,camera);}requestAnimationFrame(animate);
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
const missions=createMissions({state,save,card,btn,modal,esc,toast,begin,town:(view,place)=>{if(!ready())return;clearStage();page=view;team=false;walking=false;stick.classList.remove('visible');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===(place==='park'?'park':'plaza')));focus(place==='park'?[10,12,10]:[5,9,14],place==='park'?[8.5,.5,13.5]:[0,1.1,3.8]);locationLabel(place==='park'?'湖畔集合点':'想法广场','把想法种下，和同伴一起做成');},team:teamView});
dialog.addEventListener('close',()=>{if(page==='mission-detail'&&missions.current())missions.detail(missions.current().id);});
const townAction=element('button','town-action','＋ 发起想法');townAction.id='town-action';townAction.onclick=()=>{if(ready())missions.create();};
window.__senyou={getState:()=>({...state,page,night,team,teamMembers,ready:!!town&&!!details,avatar:avatar?.position.toArray(),visibleAvatarParts:avatar?.children.filter(o=>o.visible).map(o=>o.name),meshes:renderer.info.render.calls,triangles:renderer.info.render.triangles}),navTo,setNight};
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_town_state',description:'Read local concept demo progress without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.__senyou.getState()},{name:'navigate_town',description:'Move the visible view to an existing town location.',inputSchema:{type:'object',properties:{location:{type:'string',enum:['overview','home','plaza','park','team']}},required:['location'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!['overview','home','plaza','park','team'].includes(input.location))throw Error('Unknown location');navTo(input.location);return{page};}}])Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
