// Local, explicitly labelled concept journey. No employee records or AI API calls.
export const kinds=['运动与户外','阅读与交流','学习与创造'];
export const people=[
 {id:'p1',name:'阿禾',house:1,tags:['阅读与交流','学习与创造'],skills:['记录','整理','分享'],time:'下班后',place:'线上',note:'喜欢把散乱的想法整理成清楚的下一步。',pace:'先看背景，再确认分工'},
 {id:'p3',name:'南川',house:3,tags:['运动与户外'],skills:['场地','路线','召集'],time:'周末',place:'线下',note:'常组织轻量户外，愿意查路线和集合点。',pace:'先定集合时间，临时变化及时说'},
 {id:'p4',name:'木木',house:4,tags:['阅读与交流'],skills:['主持','交流','召集'],time:'下班后',place:'线下',note:'擅长让第一次见面的人也能自然开口。',pace:'先聊一轮，让每个人都有表达空间'},
 {id:'p5',name:'小岚',house:5,tags:['运动与户外'],skills:['陪练','场地'],time:'下班后',place:'线下',note:'羽毛球轻松打，愿意陪新手练习。',pace:'先热身、确认强度，不催进度'},
 {id:'p6',name:'清和',house:6,tags:['学习与创造','阅读与交流'],skills:['制作','设计','记录'],time:'周末',place:'线上',note:'喜欢做小作品，擅长把讨论变成看得见的草稿。',pace:'先约定一个小版本，再一起修改'},
 {id:'p10',name:'之遥',house:10,tags:['学习与创造'],skills:['分享','整理','主持'],time:'下班后',place:'线上',note:'愿意分享工作方法，也想向不同岗位的伙伴学习。',pace:'希望提前看到问题，结束时留一份清单'}
];
const templates=[
 {id:'badminton',title:'下班后，打一场不计输赢的羽毛球',kind:kinds[0],goal:'一起完成一小时友好练习，让新手也能参与。',time:'下班后',place:'线下',where:'公司附近球馆 · 集合点待共同确认',roles:['确认场地与集合','陪新手热身','准备球拍与球'],skill:['场地','陪练','召集'],owner:'p5'},
 {id:'book',title:'交换一本最近喜欢的书',kind:kinds[1],goal:'每人带来一段喜欢的文字，结束后留下一份共同书单。',time:'下班后',place:'线下',where:'附近咖啡馆 · 地点待共同确认',roles:['主持一轮分享','整理共同书单','带来分享片段'],skill:['主持','整理','分享'],owner:'p4'},
 {id:'walk',title:'周末，走一段不用赶时间的路',kind:kinds[0],goal:'一起走完一条轻松路线，找到三个想停下来的地方。',time:'周末',place:'线下',where:'城市公园 · 路线待共同确认',roles:['规划轻松路线','确认集合与天气','记录沿途发现'],skill:['路线','场地','记录'],owner:'p3'},
 {id:'learn',title:'把一个好用的工作方法教给彼此',kind:kinds[2],goal:'各演示一个节省重复劳动的方法，合写一张可复用清单。',time:'下班后',place:'线上',where:'线上共学 · 会议方式待共同确认',roles:['演示一个小方法','把方法整理成清单','主持提问与交流'],skill:['分享','整理','主持'],owner:'p10'},
 {id:'make',title:'一起做一份小镇周末漫游手册',kind:kinds[2],goal:'共同完成一页可分享的路线手册，有路线、文字和小插图。',time:'周末',place:'线上',where:'线上协作 · 工具待共同确认',roles:['整理路线素材','写一段路线介绍','做一页视觉草稿'],skill:['整理','记录','制作'],owner:'p6'}
];
const person=id=>people.find(p=>p.id===id);
const statusText={open:'寻找搭子',active:'一起行动',done:'已经做成'};
export function createMissions(ctx){
 const {state,save,card,btn,modal,esc,toast}=ctx;
 if(!state.projects){state.projects=templates.map(t=>({...structuredClone(t),id:'sample-'+t.id,source:'sample',status:'open',roles:t.roles.map((name,i)=>({name,skill:t.skill[i],member:i===0?t.owner:null,done:false})),invites:[],log:[],agreement:'',reflection:null}));}
 state.manual=state.manual||[];let filter='全部',placeFilter='',draft=null;
 const name=id=>id==='me'?state.name:person(id)?.name||'等待认领';
 const project=id=>state.projects.find(p=>p.id===id);
 const mine=p=>p.owner==='me'||p.roles.some(r=>r.member==='me');
 const persist=()=>save();
 const eligible=()=>{if(state.joined)return true;toast('先完成居民登记，再带着你的想法来。');ctx.begin();return false;};
 const chips=(items,key,value)=>items.map(t=>`<button class="choice ${value===t?'selected':''}" data-${key}="${esc(t)}" aria-pressed="${value===t}">${esc(t)}</button>`).join('');
 const localNote='<p class="demo-note">概念体验：事情、邀请、认领与进度只保存在本机；居民为虚构示例，不会通知真实员工。</p>';
 function summary(p){return `<span class="mission-category">${esc(p.kind)}</span><h3>${esc(p.title)}</h3><p>${esc(p.goal)}</p><div class="mission-meta">${esc(p.time)} · ${esc(p.place)} · ${p.roles.filter(r=>r.member).length}/${p.roles.length} 项分工已认领</div>`;}
 function board(which='全部',location=''){
  filter=which;placeFilter=location;ctx.town('missions',location==='park'?'park':'plaza');
  const done=state.projects.filter(p=>mine(p)&&p.status==='done').length;
  const list=state.projects.filter(p=>(which==='全部'||which==='我参与的'&&mine(p)||p.kind===which)&&(location!=='park'||p.kind===kinds[0]));
  card(`<p class="eyebrow">一起做成一件事 / 想法广场</p><h2>一个人的想法，<br>可以有一群人的回声。</h2><p>从一件想做的小事开始。一起行动，慢慢认识彼此。</p><div class="mission-progress"><b>${done?`已做成 ${done} 件小事`:'第一件小事，等你开始'}</b><span>种下想法 → 找到搭子 → 一起行动 → 留下经验</span></div><button id="new-project" class="primary dark">＋ 发起一件想做的事</button><div class="mission-filters">${chips(['全部','我参与的',...kinds],'filter',which)}</div>${location==='park'?'<p class="meta">正在看湖畔公园的运动与户外邀约。</p>':''}<div class="mission-list">${list.length?list.map(p=>`<button class="mission-ticket" data-project="${p.id}"><span class="mission-status">${statusText[p.status]}${p.source==='sample'?' · 示例':''}</span>${summary(p)}<span class="ticket-link">${p.status==='done'?'看看一起留下的成果':'看看需要怎样的搭子'} →</span></button>`).join(''):'<div class="mission-empty">这里还没有事情。可以发起自己的想法，也可以到“全部”里认领一个分工。</div>'}</div><button id="town-suggestion" class="text-button">给小镇写一个建议 →</button><button id="my-manual" class="text-button">我的协作经验 ${state.manual.length?'· '+state.manual.length+' 条':''} →</button>${localNote}`);
  document.querySelector('#panel').classList.add('mission-panel');btn('new-project',()=>create());btn('my-manual',manual);btn('town-suggestion',suggestion);
  document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>detail(b.dataset.project));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>board(b.dataset.filter));
 }
 function create(t=null){
  if(!eligible())return;draft=t?structuredClone(t):{title:state.wish||'',goal:'',kind:kinds[1],time:'下班后',place:'线下',where:'',roles:['','','']};
  modal(`<p class="eyebrow">种下一个想法</p><h2>你一直想做什么？</h2><p>不必是宏大的计划。写清楚一件小事，让同伴知道怎么参与。</p><div class="template-row">${templates.map(t=>`<button class="choice" data-template="${t.id}">${t.id==='badminton'?'羽毛球':t.id==='book'?'共读':t.id==='walk'?'散步':t.id==='learn'?'共学':'小作品'}</button>`).join('')}</div><form id="project-form"><label for="project-title">事情的名字</label><input id="project-title" maxlength="60" required value="${esc(draft.title)}" placeholder="例如：把一直想试的羽毛球约起来"><label for="project-goal">做成什么，就算这次完成了？</label><textarea id="project-goal" required maxlength="240" rows="2" placeholder="一个可实现、能看见的小结果">${esc(draft.goal)}</textarea><div class="form-grid"><div><label for="project-kind">想做哪类事</label><select id="project-kind">${kinds.map(v=>`<option ${draft.kind===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="project-time">大家大致何时有空</label><select id="project-time">${['下班后','周末','午休'].map(v=>`<option ${draft.time===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="form-grid"><div><label for="project-place">相遇方式</label><select id="project-place">${['线下','线上'].map(v=>`<option ${draft.place===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="project-where">地点或线上方式</label><input id="project-where" required maxlength="100" value="${esc(draft.where)}" placeholder="如：公司附近球馆，待商定"></div></div><label>需要怎样的分工？写 2–3 项</label>${[0,1,2].map(i=>`<input class="role-input" id="project-role-${i}" ${i<2?'required':''} maxlength="50" value="${esc(draft.roles[i]||'')}" placeholder="${i===0?'你愿意先认领什么？':i===1?'需要一位伙伴做什么？':'再补一项（选填）'}">`).join('')}<p class="meta">第一项由你认领，其他分工可以邀请搭子，也可以等人主动认领。</p><button class="primary dark" type="submit">把想法放到广场（本机演示）</button><p id="form-error" role="alert"></p></form>${localNote}`);
  document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>create(templates.find(t=>t.id===b.dataset.template)));
  document.querySelector('#project-form').onsubmit=e=>{e.preventDefault();const v=id=>document.getElementById(id).value.trim();const title=v('project-title'),goal=v('project-goal'),where=v('project-where'),roles=[0,1,2].map(i=>v('project-role-'+i)).filter(Boolean);if(!title||!goal||!where||roles.length<2||new Set(roles).size!==roles.length){document.getElementById('form-error').textContent='请写完整名字、完成目标、地点和至少两项不重复的分工。';return;}
   const p={id:'idea-'+crypto.randomUUID(),source:'mine',title,goal,where,kind:v('project-kind'),time:v('project-time'),place:v('project-place'),owner:'me',status:'open',roles:roles.map((name,i)=>({name,skill:guessSkill(name),member:i===0?'me':null,done:false})),invites:[],log:[],agreement:'',reflection:null};state.projects.unshift(p);state.currentProject=p.id;persist();document.querySelector('#dialog').close();detail(p.id);toast('想法已放到本机广场，接下来找一位搭子。');};
 }
 function guessSkill(s){return ['记录','整理','分享','主持','场地','路线','制作','设计','陪练','召集'].find(k=>s.includes(k))||'协作';}
 function detail(id){
  const p=project(id);if(!p)return;state.currentProject=id;persist();ctx.town('mission-detail',p.kind===kinds[0]?'park':'plaza');
  const member=mine(p),available=p.roles.filter(r=>!r.member).length;
  card(`<button id="back-board" class="text-button">← 回到想法广场</button><p class="eyebrow">${statusText[p.status]} / ${p.source==='sample'?'示例邀约':'我的想法'}</p><h2>${esc(p.title)}</h2><p>${esc(p.goal)}</p><div class="result-note">${esc(p.time)} · ${esc(p.place)}<br><span>${esc(p.where)}</span></div><h3 class="section-title">每个人，认领一小块</h3><div class="role-list">${p.roles.map((r,i)=>`<div class="role-card"><div><b>${esc(r.name)}</b><small>${esc(name(r.member))}${r.member&&r.member!=='me'?' · 示例居民':''}</small></div>${p.status==='open'&&!r.member&&!member?`<button class="choice" data-claim="${i}">我来认领</button>`:p.status==='open'&&!r.member?'<span class="meta">等一位搭子</span>':r.done?'<span class="tag">已完成</span>':''}</div>`).join('')}</div>${p.status==='open'&&member?`<button id="match-people" class="primary dark" ${available?'':'disabled'}>AI 搭子助手 · ${available?'找合适的人':'分工已满'}</button>${available?'<button id="volunteer" class="secondary">演示：有居民主动认领</button>':''}<button id="team-contract" class="secondary">一起约好，再开始</button>`:''}${p.status==='open'&&!member?'<p>看中一项分工，就认领它。无需和发起人拥有相同的性格。</p>':''}${p.status==='active'?`<div class="result-note"><b>我们的协作约定</b><br>${esc(p.agreement)}</div><button id="do-work" class="primary dark">进入行动小队</button>`:''}${p.status==='done'?`<div class="completion-card"><span>一件想法，真的留下了结果</span><h3>${esc(p.reflection?.outcome||'已完成')}</h3><p>${esc(p.reflection?.learning||'')}</p></div><button id="read-memory" class="primary dark">看看这次协作留下了什么</button>`:''}${p.invites.some(v=>v.status==='pending')?`<button id="pending-invites" class="secondary">有 ${p.invites.filter(v=>v.status==='pending').length} 份邀请等待回应（演示）</button>`:''}<button id="project-map" class="text-button">在小镇里看看这支小队 →</button>${localNote}`);
  document.querySelector('#panel').classList.add('mission-panel');btn('back-board',()=>board());btn('match-people',()=>match(id));btn('volunteer',()=>volunteer(id));btn('team-contract',()=>contract(id));btn('do-work',()=>work(id));btn('read-memory',()=>memory(id));btn('pending-invites',()=>match(id));btn('project-map',()=>ctx.team(p));
  document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{if(!eligible())return;const r=p.roles[Number(b.dataset.claim)];if(r.member||mine(p)||p.status!=='open')return;r.member='me';p.log.push(`你主动认领了「${r.name}」`);persist();detail(id);toast('已认领。先和同伴约好目标与节奏，再行动。');});
 }
 function recommendations(p,index){const role=p.roles[index];return people.filter(a=>!p.roles.some(r=>r.member===a.id)).map(a=>{const why=[],watch=[];let score=0;if(a.tags.includes(p.kind)){score+=4;why.push('对'+p.kind+'有兴趣');}if(a.time===p.time){score+=3;why.push('常用空闲时段一致');}else watch.push('时间需商量：'+a.time);if(a.place===p.place){score+=2;why.push('偏好'+p.place+'参与');}else watch.push('参与方式需确认');if(a.skills.includes(role.skill)){score+=5;why.unshift('愿意承担「'+role.skill+'」');}return {...a,score,why,watch};}).sort((a,b)=>b.score-a.score).slice(0,3);}
 function match(id,index){
  const p=project(id);if(!p||!mine(p)||p.status!=='open')return;index=index??p.roles.findIndex(r=>!r.member);if(index<0){detail(id);return;}const r=p.roles[index],rec=recommendations(p,index);
  modal(`<p class="eyebrow">AI 搭子助手 / 流程演示</p><h2>这件事，需要怎样的人？</h2><p>先看兴趣、时间、参与方式与愿意承担的分工，再聊彼此的协作节奏。不用性别或人格标签给人打分。</p><label for="match-role">这次想找人认领</label><select id="match-role">${p.roles.map((r,i)=>!r.member?`<option value="${i}" ${i===index?'selected':''}>${esc(r.name)}</option>`:'').join('')}</select><div class="candidate-list">${rec.map(a=>{const invite=p.invites.find(v=>v.person===a.id&&v.role===index&&v.status==='pending');return `<article class="candidate"><div class="candidate-heading"><b>${a.name}</b><span class="meta">示例居民 · ${a.time}</span></div><p>${a.note}</p><div class="match-reasons">${(a.why.length?a.why:['愿意尝试新协作，可先聊聊']).map(s=>`<span>${esc(s)}</span>`).join('')}</div>${a.watch.length?`<p class="match-watch">需确认：${a.watch.join('；')}</p>`:''}<p class="meta">舒服的协作方式：${a.pace}</p>${invite?`<p class="invite-pending">邀请已存入本机，等待回应</p><button class="choice" data-accept="${a.id}">演示：${a.name}接受邀请</button>`:`<button class="secondary" data-invite="${a.id}">邀请${a.name}认领</button>`}</article>`;}).join('')}<p class="demo-note">此处为规则驱动的匹配演示，未调用真实 AI，也未读取员工报告。正式版在本人同意后使用自述资料辅助推荐，邀请由对方决定。</p>`);
  document.getElementById('match-role').onchange=e=>match(id,Number(e.target.value));
  document.querySelectorAll('[data-invite]').forEach(b=>b.onclick=()=>{if(p.invites.some(v=>v.person===b.dataset.invite&&v.role===index&&v.status==='pending'))return;p.invites.push({person:b.dataset.invite,role:index,status:'pending'});persist();match(id,index);});
  document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{const inv=p.invites.find(v=>v.person===b.dataset.accept&&v.role===index&&v.status==='pending');if(!inv||r.member||p.roles.some(r=>r.member===inv.person))return;r.member=inv.person;inv.status='accepted';p.invites.filter(v=>v.role===index&&v!==inv).forEach(v=>v.status='closed');p.log.push(`${name(inv.person)}接受了「${r.name}」的邀请（示例）`);persist();document.querySelector('#dialog').close();detail(id);toast(name(inv.person)+'已在演示中加入小队。');});
 }
 function volunteer(id){const p=project(id),i=p.roles.findIndex(r=>!r.member);if(i<0)return;const a=recommendations(p,i)[0];if(!a){toast('当前示例居民都已参与，先开始现有分工吧。');return;}modal(`<p class="eyebrow">有人回应了你的想法 / 示例</p><h2>${a.name}想来帮一把。</h2><p>“我愿意认领${esc(p.roles[i].name)}。${a.note}”</p><p>先确认对方愿意做的事与时间，不用因为被推荐就立即组队。</p><div class="result-note">${a.time} · ${a.place}<br>${a.pace}</div><button id="accept-volunteer" class="primary dark">同意这项认领（演示）</button><button id="later-volunteer" class="secondary">这次先不组队</button>${localNote}`);btn('later-volunteer',()=>document.querySelector('#dialog').close());btn('accept-volunteer',()=>{if(p.roles[i].member)return;p.roles[i].member=a.id;p.log.push(`${a.name}主动认领了「${p.roles[i].name}」（示例）`);persist();document.querySelector('#dialog').close();detail(id);});}
 function contract(id){const p=project(id);if(!mine(p))return;const filled=p.roles.every(r=>r.member);modal(`<p class="eyebrow">从合得来，到做得成</p><h2>先约好，怎样一起做。</h2><p><b>共同结果：</b>${esc(p.goal)}</p><div class="contract-members">${p.roles.map(r=>`<div><b>${esc(name(r.member))}</b> · ${esc(r.name)}<small>${r.member==='me'?'你的节奏，由你自己告诉伙伴':person(r.member)?.pace||'这项还没有人认领'}</small></div>`).join('')}</div><form id="contract-form"><label for="agreement">写下你们商量好的行动约定</label><textarea id="agreement" rows="4" required maxlength="500" placeholder="例如：周六下午 3 点在湖边集合；先走一小时；临时有事提前说；结束前留 10 分钟聊聊。">${esc(p.agreement)}</textarea><p>把具体时间、地点、沟通节奏与遇到变化怎么办说清楚。示例推荐里的空闲时段，不代表已经约定。</p><label class="check-label"><input type="checkbox" id="agree-check" required> 已在本次演示中确认共同目标与各自分工</label><button class="primary dark" ${filled?'':'disabled'}>分工确认，开始一起行动</button>${filled?'':'<p class="match-watch">还有分工空着，先找到搭子再开始。</p>'}</form>${localNote}`);document.getElementById('contract-form').onsubmit=e=>{e.preventDefault();const a=document.getElementById('agreement').value.trim();if(!a||!filled)return;p.agreement=a;p.status='active';persist();document.querySelector('#dialog').close();work(id);};}
 function work(id){const p=project(id);if(!p||p.status!=='active')return;ctx.town('mission-work',p.kind===kinds[0]?'park':'plaza');card(`<p class="eyebrow">行动小队 / ${p.roles.filter(r=>r.done).length} / ${p.roles.length} 项已完成</p><h2>让想法发生在现实里。</h2><p>${esc(p.title)}</p><div class="result-note">${esc(p.agreement)}</div><p>在线下一起做，回到小镇留下进度。不以在线时长计分。</p>${p.roles.map((r,i)=>`<div class="action-item"><span>${esc(name(r.member))}${r.member!=='me'?' · 示例':''}</span><h3>${esc(r.name)}</h3><button class="secondary" data-finish="${i}" aria-pressed="${r.done}">${r.done?'✓ 已完成，点击可撤回':r.member==='me'?'我完成了这项分工':'演示：'+name(r.member)+'完成了'}</button></div>`).join('')}<button id="reflect" class="primary dark" ${p.roles.every(r=>r.done)?'':'disabled'}>一起复盘，留下成果</button><button id="work-back" class="text-button">回到事情详情 →</button>${localNote}`);document.querySelector('#panel').classList.add('mission-panel');document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>{const r=p.roles[Number(b.dataset.finish)];r.done=!r.done;persist();work(id);});btn('reflect',()=>reflect(id));btn('work-back',()=>detail(id));}
 function reflect(id){const p=project(id);if(!mine(p)||!p.roles.every(r=>r.done))return;modal(`<p class="eyebrow">把一起做过的事，变成彼此的了解</p><h2>这一次，我们做成了什么？</h2><form id="reflection-form"><label for="outcome">留下一个真实的小结果</label><textarea id="outcome" required maxlength="400" rows="3" placeholder="例如：四个人一起打完一小时球，新手也完成了第一次双打。"></textarea><label for="learning">这次协作，让你更了解自己的哪一点？</label><textarea id="learning" required maxlength="400" rows="3" placeholder="例如：我很愿意组织，但希望临时变更能提前告诉我。"></textarea><label for="next-time">下次合作，希望彼此怎样配合？</label><textarea id="next-time" required maxlength="300" rows="2" placeholder="一条具体、可尝试的协作约定"></textarea><button class="primary dark">保存成果与协作经验</button></form><p class="demo-note">请记录自己的体验，不把示例居民的表现当成真实反馈。正式版邀请参与者各自补充感受，不代替他人评价。</p>`);document.getElementById('reflection-form').onsubmit=e=>{e.preventDefault();const val=id=>document.getElementById(id).value.trim();const outcome=val('outcome'),learning=val('learning'),next=val('next-time');if(!outcome||!learning||!next)return;p.reflection={outcome,learning,next};p.status='done';const entry={projectId:p.id,title:p.title,role:p.roles.find(r=>r.member==='me')?.name||'参与协作',...p.reflection};state.manual=state.manual.filter(e=>e.projectId!==p.id);state.manual.push(entry);persist();document.querySelector('#dialog').close();memory(id);};}
 function memory(id){const p=project(id);ctx.town('mission-memory','plaza');card(`<p class="eyebrow">一件小事，成为小镇的一段共同记忆</p><h2>不是认识了几个人，<br>是一起做成了一件事。</h2><div class="completion-card"><span>${esc(p.title)}</span><h3>${esc(p.reflection.outcome)}</h3><p>${p.roles.map(r=>esc(name(r.member))).join(' · ')}</p></div><h3 class="section-title">写进我的协作说明书</h3><div class="result-note"><b>这次更了解自己</b><br>${esc(p.reflection.learning)}<br><br><b>下次试着这样配合</b><br>${esc(p.reflection.next)}</div><p>这不是人格结论，而是一次具体协作留下的经验。</p><button id="next-idea" class="primary dark">还有一件事，想和大家一起做</button><button id="memory-manual" class="secondary">查看我的协作经验</button><button id="memory-board" class="text-button">回到广场看看别人的想法 →</button>${localNote}`);document.querySelector('#panel').classList.add('mission-panel');btn('next-idea',()=>create());btn('memory-manual',manual);btn('memory-board',()=>board());}
 function suggestion(){modal('<h2>给小镇的一个建议</h2><label for="suggestion">你希望小镇多出什么？</label><textarea id="suggestion" rows="4" maxlength="300"></textarea><button id="save-suggestion" class="primary dark">存进我的演示信箱</button><p class="demo-note">仅保存到本机，不会提交给项目团队。</p>');document.getElementById('suggestion').value=state.suggestion||'';btn('save-suggestion',()=>{const t=document.getElementById('suggestion').value.trim();if(!t){toast('写下你的想法再存入吧。');return;}state.suggestion=t;persist();document.querySelector('#dialog').close();toast('建议已存入本机演示信箱。');});}
 function manual(){modal(`<p class="eyebrow">我的协作说明书 / 实践补充</p><h2>我在一起做事中，<br>慢慢认识自己。</h2>${state.manual.length?state.manual.map(e=>`<article class="candidate"><h3>${esc(e.title)}</h3><p class="meta">我认领了：${esc(e.role)}</p><p>${esc(e.learning)}</p><div class="result-note">下次配合：${esc(e.next)}</div><p class="meta">来源：本机概念体验中的个人复盘，不是正式测评。</p></article>`).join(''):'<p>还没有协作记录。先发起或认领一件小事，完成后把自己的发现留在这里。</p>'}<p class="demo-note">专业 DISC 报告与实践经验应分开呈现。这里不会根据活动或性别推断人格。</p>`);}
 return {board,create,detail,work,manual,current:()=>project(state.currentProject),openCurrent:()=>{const p=project(state.currentProject);p?detail(p.id):board('我参与的');},members:p=>p.roles.filter(r=>r.member).map(r=>({id:r.member,name:name(r.member),house:r.member==='me'?state.home:person(r.member)?.house,role:r.name,pace:r.member==='me'?'把你的偏好告诉同伴':person(r.member)?.pace})),templates};
}
