import {QUESTIONS,makeProfile} from './opening-content.js?v=grove3';
import {buildStory} from './opening-story.js?v=grove3';
import {archiveMarkup,tableMarkup,escapeHTML as e} from './opening-cards.js?v=grove3';
import qrcode from './vendor/qrcode.mjs';

const btn=(action,text,cls='',extra='')=>`<button data-action="${action}" class="${cls}" ${extra}>${text}</button>`;
export const TOUR_STEPS=['认识主人','打开档案袋','坐到会客桌','一起做件小事'];
export function readInvitation(search){const q=new URLSearchParams(search),raw=q.get('room');return {present:q.has('room'),valid:/^[a-f0-9]{16}$/i.test(raw||''),code:(raw||'').toLowerCase(),name:(q.get('activity')||'森友小镇开张日').trim().slice(0,40)};}
export function invitationURL(base,code,name){if(!/^[a-f0-9]{16}$/.test(code))throw Error('活动邀请码无效');const u=new URL(base);u.search='';u.hash='';u.searchParams.set('room',code);u.searchParams.set('activity',String(name||'森友小镇开张日').slice(0,40));return u.href;}
export function invitationQR(url){const qr=qrcode(0,'M');qr.addData(url);qr.make();return qr.createSvgTag({cellSize:6,margin:24,scalable:true});}
export function tourResident(){const answers=Object.fromEntries(QUESTIONS.map(q=>[q.id,3]));const profile=makeProfile(answers,{experience:'示例故事：我曾和伙伴一起整理活动路线，把容易遗漏的细节放进一张检查表。',offer:'这次共建，我想和伙伴一起做一张清楚的入住地图。'});profile.story=buildStory(profile);profile.support='';return {id:'tour-resident',name:'小林',demo:true,ready:true,profile,appearance:{body:'neutral',hairstyle:1,skin:'#deb896',hair:'#594334',outfit:'#a0ad87'},houseColor:'#829475'};}
export function welcomeMarkup(ready){return `<h1>在森林里，<br>认识一起做事的彼此。</h1><p class="entry-intro">把自己的做事习惯，放进一间小屋；<br>去邻居家坐坐，看看怎样合作更舒服；<br>再一起完成一件小事，让小镇里的树长起来。</p>${btn('tour-start','先逛一逛小镇','primary entry-primary')}<p class="entry-caption">不用填写资料，先看一间示例小屋。</p><section class="training-callout"><strong>正式培训时，学员扫码直接入住</strong><p>老师展示活动二维码，大家扫码后直接准备自己的小屋，不用选择进入方式。</p>${btn('training-info','看看培训现场怎么玩','text-button')}</section><div class="entry-links"><span>已收到活动邀请？${btn('join-form','输入邀请码','text-button')}</span>${btn('host-form','组织一场活动','text-button')}</div>${ready?btn('start-demo','继续我的个人体验','text-button resume-demo'):''}<small class="entry-boundary">创意体验版 · 非专业 DISC 测评 · 不产生真实捐种</small>`;}
export function tourMarkup(step,r,ready){const p=r.profile;const body=[`<h2>先认识小屋的主人</h2><p>小屋不是一套答题结果，而是让邻居认识你的地方。</p><div class="archive-sheet"><div class="folder-tab">小林的居民木牌</div><h3>有个问题想理清楚，欢迎敲门。</h3><p>${e(p.offer)}</p></div><p class="muted">正式活动里，这里会换成你自己选择的形象、门牌和介绍。</p>`,`<h2>看看他怎样做事</h2><p class="tour-caption">先用一句话记住他，想多了解时再展开。</p>${archiveMarkup(p,r.name,false)}`,`<h2>怎样合作，更舒服？</h2>${tableMarkup(p,true,false,r.id)}<p class="tour-caption">真实邻居在这里聊一聊，再共同确认合作约定。</p>`,`<h2>认识彼此，是为了<br>一起把事情做好。</h2><p>例如，一起为新居民做一张入住地图：商量取舍、明确分工，再共同提交。</p><ol class="training-steps compact"><li><strong>找到伙伴</strong><span>用刚才了解的习惯，约好怎样合作。</span></li><li><strong>完成一件小事</strong><span>共同交付项目，获得协作能量。</span></li><li><strong>留下成长</strong><span>收取能量、一起浇水，再修订自己的协作说明书。</span></li></ol><p class="muted">画面为成长示意，不是你的实际能量记录。</p>`][step];return `<div class="row spread"><small>示例导览 · 不是真实居民或你的测评结果</small>${btn('entry-home','返回首页','text-button')}</div><nav class="tour-tabs" aria-label="示例导览步骤">${TOUR_STEPS.map((s,i)=>btn('tour-step',`${i+1}. ${s}`,i===step?'selected':'',`data-step="${i}" aria-current="${i===step?'step':'false'}"`)).join('')}</nav>${body}<div class="actions">${step?btn('tour-step','上一步','',`data-step="${step-1}"`):''}${step<3?btn('tour-step',['打开他的档案袋','到会客桌坐坐','看看怎样一起做事'][step],'green',`data-step="${step+1}"`):btn('start-demo',ready?'用我的档案继续体验':'布置我的小屋','primary')}</div>${step===3?`<p class="muted">个人体验有预设邻居；正式培训连接现场同事。</p>${btn('training-info','培训时，大家如何一起进入？','text-button')}`:''}`;}
export function trainingMarkup(){return `<div class="row spread"><small>正式培训 · 同一个小镇，真实的同事</small>${btn('entry-home','返回首页','text-button')}</div><h2>现场扫一个码，<br>大家一起入住。</h2><p>给合作伙伴看的导览，与学员参加活动，是两条不同的入口。</p><ol class="training-steps"><li><strong>老师创建活动，展示二维码</strong><span>二维码已经带上本场邀请码。</span></li><li><strong>学员扫码，直接开始入住</strong><span>确认参与后设置形象、回答情境问题，不用再选“加入”或“主持”。</span></li><li><strong>把自己的习惯，放进小屋</strong><span>亲自确认短介绍、档案袋和会客便签。</span></li><li><strong>老师开放串门，大家找伙伴共建</strong><span>走访真实同事，确认合作、共同交付，再一起浇灌合种林。</span></li><li><strong>带走今天的新发现</strong><span>修订协作说明书，下载居民卡与合种纪念。</span></li></ol><div class="stack entry-stack">${btn('preview-invitation','预览学员扫码后看到的页面','primary')}${btn('host-form','我是组织者，创建活动')}</div><p class="muted">活动期间，组织者需保持页面在线。正式培训前，应使用现场设备与网络试连。</p>`;}
export function invitationMarkup(inv,{preview=false,busy=false,error='',ready=false}={}){if(!inv.valid&&!preview)return `<h2>这个活动邀请不完整</h2><p>请重新扫描老师展示的二维码，或请老师发一个新的邀请链接。</p><div class="stack">${btn('join-form','手动输入邀请码','primary')}${btn('entry-home','先了解一下小镇')}</div>`;return `${preview?'<div class="notice">学员视角预览 · 不会连接或加入任何活动</div>':''}<h1>欢迎来到<br>${e(inv.name)}</h1><p class="entry-intro">今天，你将和现场的同事一起入住小镇。<br>先准备自己的小屋，稍后一起串门、寻找合作伙伴。</p><ol class="arrival-steps"><li>选一个自己的形象</li><li>写下做事与沟通习惯</li><li>确认小屋，等待老师开放串门</li></ol>${preview?`<div class="example-cta">开始准备我的小屋</div><p class="muted">真实活动中，学员确认参与后，点这一个按钮即可开始。无需再次填写邀请码或选择角色。</p>${btn('training-info','返回培训流程','green')}`:`<p class="entry-caption">已带入本场邀请码，无需再次输入。${ready?'本机已有你的档案，加入后可查看或修改。':''}</p><form id="invitation-form"><label class="check"><input type="checkbox" name="consent" required ${busy?'checked disabled':''}>我愿意参加本场活动，同意通过实时连接分享本人确认的资料；使用昵称，不填写敏感信息。</label><button class="primary entry-primary" type="submit" ${busy?'disabled':''}>${busy?'正在连接，请稍候…':ready?'带上我的小屋，进入活动':'开始准备我的小屋'}</button></form>${error?`<div class="notice warning" role="alert">${e(error)}<p>请确认老师已开启活动且保持在线，然后重试；微信内无法连接时，可尝试用系统浏览器打开。</p></div>`:''}<p class="muted">实时连接使用 PeerJS / WebRTC。组织者在线保管本场资料，原始答题只留在你的浏览器。</p>${btn('join-form','换一个邀请码','text-button')}`}`;}
