import {ForestWorld} from './opening-world.js?v=grove3';
import {icon} from './opening-icons.js?v=grove3';
import {TownSession,energy,standings} from './opening-session.js?v=entry4';
import {QUESTIONS,CHAPTERS,PHASES,PROJECTS,DISCLAIMER,makeProfile,SOURCES} from './opening-content.js?v=grove3';
import {buildStory,confirmedStory,STORY_FIELDS} from './opening-story.js?v=grove3';
import {wallet,growthState} from './opening-energy.js?v=grove3';
import {archiveMarkup,tableMarkup,storyEditor,pairMarkup,energyMarkup} from './opening-cards.js?v=grove3';
import {welcomeMarkup,tourMarkup,tourResident,trainingMarkup,invitationMarkup,readInvitation,invitationURL,invitationQR} from './opening-entry.js?v=entry4';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved;try{saved=JSON.parse(localStorage.getItem('senyou-opening-person')||'null');}catch{}
const person={name:'',appearance:{body:'neutral',hairstyle:1,skin:'#deb896',hair:'#594334',outfit:'#a0ad87'},houseColor:'#829475',answers:{},profile:null,ready:false,shareSupport:false,...saved};
let invitation=readInvitation(location.search),page=invitation.present?'invitation':'welcome',tourStep=0,entering=false,entryError='',questionIndex=0,visitId=null,section='door',room=null,world,worldReady=false,activeProject=null,connectionStatus='',pendingMode='demo';
const sampleResident=tourResident();
const panel=$('#panel'),dialog=$('#dialog'),session=new TownSession(onRoom,setStatus,toast);
for(const [action,name] of [['home','home'],['map','map'],['commons','people'],['inbox','mail'],['host','tree']])$('#navigation').querySelector(`[data-action="${action}"]`).insertAdjacentHTML('afterbegin',icon(name));
function save(){try{localStorage.setItem('senyou-opening-person',JSON.stringify(person));}catch{toast('未能保存到本机，请及时下载居民卡。');}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function setStatus(message){connectionStatus=message;$('#status').textContent=message;}
function publicPerson(){return {name:person.name||'新居民',appearance:person.appearance,houseColor:person.houseColor,ready:person.ready,profile:{...(person.profile||{}),support:person.shareSupport?person.profile?.support:''}};}
function onRoom(data){const previousPhase=room?.phase,previousEnergy=room?energy(room):null;room=data;$('#exit-session').hidden=false;const ready=Object.values(room.residents).filter(r=>r.ready);world?.setResidents(ready);world?.setLocalResident(data.residents[session.id]);world?.setGrove(growthState(room),wallet(room,session.id).pending,room.townName,room.phase===3);if(previousEnergy!==null&&energy(room)>previousEnergy)world?.pour();world?.setProjects(room.projects);$('#phase-label').textContent=PHASES[room.phase];$('#host-nav').hidden=!['host','demo'].includes(session.mode);$('#mail-count').textContent=room.messages.filter(m=>m.to===session.id).length||'';
 if(room.phase===3&&previousPhase!==3&&person.ready&&page!=='welcome'){page='ceremony';world?.showTown();render();toast('小镇开张了，一起看看今天留下的成果。');}
 else if(page==='waiting'&&room.phase>0&&person.ready){page='map';world?.showTown();render();toast('小镇开放串门了，带着你的共建兴趣去认识邻居吧。');}
 else if(page==='project'&&$('#project-form')?.dataset.dirty==='true'){if(Number($('#project-form').dataset.revision)!==(room.projects[activeProject]?.draftRevision||0))$('#project-sync').hidden=false;}
 else if(['host','waiting','map','inbox','commons','ceremony','project'].includes(page)&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))render();
 if(page==='home'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))render();
}
function setPage(next){page=next;panel.scrollTop=0;render();if(innerWidth<=800&&['welcome','tour','training','invitation','invite-preview'].includes(next))window.scrollTo({top:0,behavior:'instant'});}
function button(action,text,cls='',attrs=''){return `<button data-action="${action}" class="${cls}" ${attrs}>${text}</button>`;}
function gate(){if(!person.ready){toast('先完成入住，让邻居认识你。');return false;}if(!room||room.phase<1){setPage('waiting');return false;}return true;}
async function send(type,payload){try{await session.send(type,payload);return true;}catch(e){toast(e.message);return false;}}
function showHome(id,part='door'){const resident=room?.residents[id];if(!resident)return;if(id!==session.id&&!gate())return;visitId=id;section=part;page='home';if(id!==session.id)send('visit',{to:id});else send('presence',{location:'小屋'});world?.showHome(resident,part);render();}
function modal(html){$('#dialog-content').innerHTML=html;dialog.showModal();}
function resetPreview(){world?.setLocalResident(null);world?.setResidents([]);world?.setProjects({});world?.setEnergy(0);world?.showTown();}
function showTour(step=0){if(!worldReady)return toast('小镇还在载入，请稍等。');tourStep=Math.max(0,Math.min(3,Number(step)||0));if(tourStep<3)world.showHome(sampleResident,['door','archive','table'][tourStep]);else{world.setResidents([sampleResident]);world.setLocalResident(null);world.setGrove({value:14,progress:.7},0,'一起做事，一起生长',false,true);world.setProjects({welcome:{submitted:true,choices:[0,2]}});world.showTown();world.focusGrove();}setPage('tour');}
function showInvitation(code,name='森友小镇开张日'){invitation=readInvitation('?'+new URLSearchParams({room:code,activity:name}));entryError='';dialog.close();resetPreview();setPage('invitation');}
function activityInvite(){return invitationURL(location.href,session.code,room.activityName);}
function showInviteQR(){const url=activityInvite();modal(`<div class="invite-poster"><small>本场活动 · 学员入口</small><h2>${esc(room.activityName||'森友小镇开张日')}</h2><p>扫码直接准备你的小屋</p><div class="invite-qr" role="img" aria-label="本场活动入住二维码">${invitationQR(url)}</div><p>不用选择角色，不用再次填写邀请码。</p><small>备用邀请码：${esc(session.code)}</small><div class="actions">${button('copy-invite','复制学员邀请链接','green')}${button('download-invite','下载二维码')}</div><p class="muted">请在学员进入和活动期间保持本页在线。${['localhost','127.0.0.1'].includes(location.hostname)?'当前为本机测试地址，手机扫码不可访问；正式使用请在上线网址创建活动。':''}</p></div>`);}
$('#close-dialog').onclick=()=>dialog.close();
function avatar(){const a=person.appearance;return `<div class="chapter">入住准备 · 先让邻居认出你</div><h2>这一次，以你的样子</h2><p>形象由你选择。接下来的森林问答，会帮助你写下自己的做事习惯。</p><label for="name">居民昵称</label><input id="name" maxlength="20" placeholder="你希望邻居怎样称呼你" value="${esc(person.name)}"><label for="body">形象轮廓</label><select id="body">${[['neutral','自在'],['female','柔和'],['male','利落']].map(([v,t])=>`<option value="${v}" ${v===a.body?'selected':''}>${t}</option>`).join('')}</select><label>发型</label><div class="row">${['短发','侧分','齐耳','马尾'].map((n,i)=>button('hair-style',n,a.hairstyle===i?'selected':'',`data-value="${i}"`)).join('')}</div>${swatches('肤色','skin',['#f0d0b0','#deb896','#b98058','#865c43'])}${swatches('发色','hair',['#594334','#312e2a','#ac8052','#8b8b82'])}${swatches('衣服','outfit',['#a0ad87','#c78160','#8099ac','#e5d5b7'])}${swatches('小屋点缀色','houseColor',['#829475','#c78160','#8aa8a0','#b8a078'])}<div class="actions">${person.ready?button('save-avatar','保存形象，回到小屋','primary'):button('begin-questions','带上自己，去认识森林','primary')}</div><p class="muted">24 个情境 · 三个章节 · 可随时返回修改，自动保存在本机。</p>`;}
function swatches(label,key,colors){return `<label>${label}</label><div class="color-options">${colors.map(c=>`<button class="swatch ${(key==='houseColor'?person.houseColor:person.appearance[key])===c?'selected':''}" style="background:${c}" aria-label="${label} ${c}" data-action="color" data-key="${key}" data-value="${c}"></button>`).join('')}</div>`;}
function questionnaire(){const q=QUESTIONS[questionIndex],selected=person.answers[q.id],count=QUESTIONS.filter(q=>Number.isInteger(person.answers[q.id])).length;const preview=makeProfile(person.answers);return `<div class="row spread"><span class="chapter">${CHAPTERS[q.chapter]}</span><span class="muted">${questionIndex+1} / ${QUESTIONS.length}</span></div><div class="progress-track"><div style="width:${count/24*100}%"></div></div><h2>${q.title}</h2><p>${q.context}</p><div class="question-options">${q.options.map((o,i)=>button('answer',esc(o.label),selected===i?'selected':'',`data-index="${i}" aria-pressed="${selected===i}"`)).join('')}</div><div class="actions">${button('question-prev',questionIndex?'上一题':'回到形象')}${button('question-next',questionIndex===23?'整理我的档案':'下一题','primary',Number.isInteger(selected)?'':'disabled')}</div><p class="save-state">已记录 ${count} 个选择 · 自动保存在本机</p>${count?`<div class="profile-preview"><small>档案正在形成</small><p>${esc(q.options[selected]?.note||preview.habits.split('\n')[0]||'继续探索，你会逐步看见自己的合作习惯。')}</p></div>`:''}<details><summary class="muted">题目与专业测评的区别</summary><p class="muted">${DISCLAIMER}</p></details>`;}
const fields=[['intro','门牌上的一句话'],['habits','森友档案 · 我的做事习惯'],['experience','我做过的事（自己补充，可留空）'],['offer','这次共建，我愿意参与什么（自己补充）'],['communication','会客桌 · 怎样和我沟通'],['support','我希望得到的支持（默认仅自己看）'],['growth','下次合作，我想试着调整什么']];
function review(){person.profile||=makeProfile(person.answers);return `<div class="chapter">入住前 · 请你亲自确认</div><h2>这像我吗？</h2><p>为档案袋写一张短介绍，在会客桌留三张便签。原有资料完整保留，私密支持不会进入公开短介绍。</p><form id="profile-form">${storyEditor(person.profile)}<details class="paper-fold"><summary>完整自述、门牌与自己的故事</summary>${fields.map(([k,label])=>`<label for="f-${k}">${label}</label><textarea id="f-${k}" name="${k}" maxlength="${k==='intro'?100:1200}" ${k==='intro'?'required':''}>${esc(person.profile[k])}</textarea>`).join('')}</details><label class="check"><input type="checkbox" name="shareSupport" ${person.shareSupport?'checked':''}>我愿意向本场居民分享“希望得到的支持”</label><label class="check"><input type="checkbox" name="consent" required>我已检查短介绍、便签和完整自述，同意分享以上可见资料。</label><button class="primary" type="submit">这些像我，确认分享</button></form><p class="muted">原始答题仅留在本机。归纳由本地文字模板完成，不把资料交给外部 AI。</p>`;}
function waiting(){const all=Object.values(room?.residents||{}).filter(r=>r.id!==room.organizerId||r.ready),ready=all.filter(r=>r.ready);return `<h2>小屋准备好了</h2><p>你的木牌、档案袋和会客桌已经就位。等主持人开放街区，我们再去认识邻居。</p><div class="big-number">${ready.length} / ${all.length}</div><p class="muted">已完成入住的居民</p><div class="stack">${button('home','先看看我的小屋','green')}${['host','demo'].includes(session.mode)?button('host','去主持台开放串门','primary'):button('reconnect','重新连接场次')}</div><p class="muted">${esc(connectionStatus)}</p>`;}
function map(){const list=Object.values(room.residents).filter(r=>r.ready);return `<div class="chapter">${PHASES[room.phase]} · ${list.length} 位居民</div><h2>带着一件想做的事，<br>去敲邻居的门</h2><p>看看彼此的习惯，聊聊想参与的共建。不必找最像你的人。</p><p class="muted">点地面可以散步，拖动画面可以环顾。点小屋木牌进入；你的散步位置仅在自己屏幕显示。</p>${session.mode==='demo'?'<div class="notice">阿禾、青岚、小满是预设体验居民。真实场次只显示实际加入的人。</div>':''}<div class="resident-list">${list.map(r=>`<button class="resident-row" data-action="visit" data-id="${esc(r.id)}"><span class="initial">${esc(r.name.slice(0,1))}</span><span><strong>${esc(r.name)}${r.id===session.id?' · 我':''}</strong><small>${r.demo?'预设体验居民':r.online?'在小镇中':'暂时离开 · 可以留言'}</small><small>${esc(r.profile.intro)}</small></span></button>`).join('')}</div><div class="actions">${button('commons','看看共建项目','green')}</div>`;}
function home(){const r=room.residents[visitId]||room.residents[session.id],own=r.id===session.id,p=own?person.profile:r.profile;return `<div class="row spread"><span class="chapter">${own?'我的小屋':esc(r.name)+'的小屋'}</span>${button('map','回到小镇','small')}</div><h2>${section==='door'?'你好，我是'+esc(r.name):({archive:'打开森友档案袋',table:'在窗边，坐下来聊聊',mail:'留一封森林来信'})[section]}</h2><div class="section-tabs">${[['door','居民木牌'],['archive','档案袋'],['table','会客桌'],['mail','信箱']].map(([id,t])=>button('section',t,section===id?'selected':'',`data-id="${id}"`)).join('')}</div>${section==='door'?`<div class="paper-text">${esc(p.intro||'愿意认识一起做事的邻居。')}</div><p>${esc(p.offer||'还没写下这次想参与的事，可以来聊聊。')}</p><p class="muted">${r.demo?'预设体验居民，不是真实在线同事':r.online?'正在小镇中':'现在不在家。你可以阅读已分享的档案，留一封信。'}</p>`:section==='archive'?archiveMarkup(p,r.name,own):section==='table'?tableMarkup(p,own,person.shareSupport,r.id):mailView(r.id)}${own&&section!=='mail'?`<div class="actions">${button('edit-profile','修改档案')}${button('edit-avatar','调整形象')}${button('download','带走居民卡','primary')}</div>`:''}<p class="muted">本人确认的自我描述，可随经历继续修改。</p>`;}
function mailView(id){if(id===session.id)return inbox();const r=room.residents[id];const ms=room.messages.filter(m=>(m.from===session.id&&m.to===id)||(m.from===id&&m.to===session.id));return `<p>${r.demo?'这是一位预设邻居。留言可在本机保存，不会伪造对方回复。':r.online?'可以留言聊聊，对方会在信箱收到。':'邻居不在家也可以留言，回来连接本场后就能看到。'}</p>${ms.map(message).join('')}<form id="message-form" data-to="${esc(id)}"><label for="message-body">我想和你聊聊</label><textarea id="message-body" name="body" required maxlength="500" placeholder="比如，我们一起做欢迎站吧。我愿意先整理路线，你想参与哪部分？"></textarea><button class="primary" type="submit">放进信箱</button></form><p class="muted">真实场次由主持人在线保管留言；场次结束后不承诺云端留存。</p>`;}
function message(m){const from=room.residents[m.from]?.name||'居民';return `<div class="message ${m.from===session.id?'sent':''}"><small>${esc(from)} · ${new Date(m.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</small><p>${esc(m.body)}</p>${m.to===session.id?button('reply','回复','small',`data-id="${esc(m.from)}"`):''}</div>`;}
function inbox(){const messages=room.messages;const agreements=room.agreements;return `<h3>我的信箱</h3>${messages.length?messages.slice().reverse().map(message).join(''):'<p>还没有来信。先去认识一位邻居吧。</p>'}<h3>我们留下的约定</h3>${agreements.length?agreements.map(a=>`<div class="message"><small>${esc(room.residents[a.from]?.name)} × ${esc(room.residents[a.to]?.name)} · ${a.accepted?'双方已确认':'等待对方确认'}</small><p>${esc(a.text)}</p>${!a.accepted&&a.to===session.id?button('accept','我也同意这条约定','green',`data-id="${a.id}"`):''}${!a.accepted&&session.mode==='demo'?button('simulate-accept','演示对方确认（模拟）','small',`data-id="${a.id}"`):''}</div>`).join(''):'<p class="muted">聊完合作方式后，可以邀请邻居共同确认一条约定。</p>'}`;}
function commons(){return `<h2>合种广场</h2><p>把一次合作，变成一份看得见的生长。</p>${energyMarkup(room,session.id)}${room.phase<2?`<div class="notice">先去串门，确认一份合作或支持。主持人开启共建后，可以加入公共项目。</div>${['demo','host'].includes(session.mode)?button('phase','进入一起共建','green','data-value="2"'):''}`:''}<h3>一起为小镇做点事</h3>${PROJECTS.map(def=>{const p=room.projects[def.id];return `<div class="project"><h3>${def.name}</h3><p>${def.brief}</p><small>${esc(p?.members.map(id=>room.residents[id]?.name).join('、')||'等待居民加入')}${p?.submitted?' · 已完成':''}</small><div class="actions">${button('project-view',p?.submitted?'看看共同成果':'了解与共建',p?.submitted?'':'green',`data-id="${def.id}"`)}</div></div>`;}).join('')}<details class="paper-fold"><summary>查看公共项目进展</summary>${standings(room).map(p=>`<div class="scoreline"><span>${p.name}</span><span>${p.submitted?'已交付':(p.members?.length||0)+' 人参与'}</span></div>`).join('')}</details>${['demo','host'].includes(session.mode)?button('host','去主持台准备开张'):''}`;}
function project(){const d=PROJECTS.find(p=>p.id===activeProject),p=room.projects[d.id],joined=p?.members.includes(session.id);return `<div class="chapter">共建项目</div><h2>${d.name}</h2><p>${d.brief}</p><div class="notice">${d.challenge}</div><p class="muted">成员：${esc(p?.members.map(id=>room.residents[id]?.name).join('、')||'暂无')}</p>${!joined&&!p?.submitted?button('project-join','我想参与这个项目','green',`data-id="${d.id}" ${room.phase!==2?'disabled':''}`):''}${joined&&session.mode==='demo'&&p.members.length<2?button('simulate-project','邀请体验居民加入（模拟）','small',`data-id="${d.id}"`):''}${joined&&!p?.submitted&&p?.text?`<div class="notice">当前稿件已获 ${p.approvals?.filter(id=>p.members.includes(id)).length||0} 位成员确认。内容修改后需重新确认。</div><div class="actions">${button('approve-project','我确认这版方案','green',`data-id="${d.id}" data-revision="${p?.draftRevision||0}"`)}${session.mode==='demo'?button('simulate-approval','演示伙伴确认（模拟）','small',`data-id="${d.id}"`):''}</div>`:''}<div id="project-sync" class="notice" hidden>伙伴已更新讨论稿。请先复制要保留的文字。${button('reload-project','读取新稿（替换未保存内容）','small')}</div><form id="project-form" data-revision="${p?.draftRevision||0}"><fieldset ${!joined||p?.submitted?'disabled':''} style="border:0;padding:0"><h3>我们选择的设施</h3>${d.options.map(([label,cost],i)=>`<label class="check"><input type="checkbox" name="choice" value="${i}" ${p?.choices.includes(i)?'checked':''}>${label} · ${cost} 份材料</label>`).join('')}<label for="project-text">为什么这样选？谁来负责？怎样协作？</label><textarea id="project-text" name="text" maxlength="1200" placeholder="写下你们的取舍、分工和共同约定。">${esc(p?.text||'')}</textarea><div class="actions"><button type="submit" name="intent" value="save">保存讨论稿</button><button class="primary" type="submit" name="intent" value="submit">共同提交</button></div></fieldset></form>${p?.submitted?'<div class="notice">这份共同成果已计入开张仪式。</div>':''}<div class="actions">${button('commons','回到广场')}</div>`;}
function host(){const members=Object.values(room.residents).filter(r=>r.id!==session.id||r.ready),ready=members.filter(r=>r.ready),submitted=Object.values(room.projects).filter(p=>p.submitted).length;return `<div class="chapter">${session.mode==='demo'?'独自体验 · 流程控制':'主持人控制台'}</div><h2>${session.mode==='host'?esc(room.activityName||'森友小镇开张日'):'让小镇，一起开张'}</h2>${session.mode==='host'?`<section class="host-invite"><p>第一步，把二维码展示给学员。扫码即可直接开始入住。</p>${button('show-invite-qr','展示学员入住二维码','primary')}<div class="row">${button('copy-invite','复制学员邀请链接','small')}${button('copy-code','复制备用邀请码','small')}</div></section><p class="muted">主持人请保持本页面开启。此场最多 60 人，企业网络可能限制 WebRTC；正式活动前请用现场设备试连。</p>`:'<p>你可以自行切换阶段。真实培训场次只有主持人可以操作。</p>'}<div class="divider"></div><div class="row"><span class="big-number">${ready.length}/${members.length}</span><span>学员已入住<br><small>${submitted} 个项目已交付</small></span></div><div class="stack">${PHASES.map((name,i)=>button('phase',`${i+1}. ${name}`,room.phase===i?'selected':'',`data-value="${i}"`)).join('')}</div><p class="muted">建议流程：5 分钟介绍 → 15 分钟形象与问答 → 10 分钟确认档案 → 10 分钟串门 → 15 分钟共建 → 5 分钟开张复盘。</p><h3>居民准备情况</h3>${members.map(r=>`<div class="scoreline"><span>${esc(r.name)}</span><span>${r.ready?'已就绪':'布置中'} · ${r.online?'在线':'离线'}</span></div>`).join('')}<div class="actions">${button('home','准备我的小屋（可选）')}${button('export-room','下载本场公共成果')}${button('leave-session','离开场次')}</div>`;}
function ceremony(){return `<div class="celebration"><div class="stamp">共同种下<br>今日留念</div><h1>${esc(room.townName)}</h1><p>${Object.values(room.residents).filter(r=>r.ready).length} 位居民一起参与，${Object.values(room.projects).filter(p=>p.submitted).length} 个公共项目已交付。</p><div class="grove-signature">${Object.values(room.residents).filter(r=>r.ready).map(r=>`<span>${esc(r.name)}${r.demo?'（模拟）':''}</span>`).join('')}</div>${energyMarkup(room,session.id)}<h3>今天留下的公共成果</h3>${Object.values(room.projects).filter(p=>p.submitted).map(p=>`<div class="project"><strong>${PROJECTS.find(d=>d.id===p.id).name}</strong><p>${esc(p.text)}</p></div>`).join('')}<label for="reflection">刚才的合作，让我更了解自己的一点</label><textarea id="reflection" placeholder="哪一句说明需要改一改？下一次你想尝试什么？">${esc(person.reflection||'')}</textarea><div class="stack">${button('save-reflection','记下今天的发现','green')}${button('download','带走我的居民卡','primary')}${button('grove-memento','下载本场合种纪念')}${button('edit-profile','回小屋，修订说明书')}</div><p class="muted">树木生长为游戏中的时间压缩。此页为活动纪念，不是官方植树证书，不产生真实种植或碳减排。</p></div>`;}
function render(){const entry=['welcome','tour','training','invitation','invite-preview'].includes(page);panel.classList.toggle('welcome',page==='welcome');panel.classList.toggle('entry-panel',entry);panel.classList.toggle('reading',(page==='home'&&['archive','table'].includes(section))||page==='tour');panel.classList.toggle('wide',['review','project','ceremony'].includes(page));$('#navigation').hidden=session.mode==='none'||(!person.ready&&session.mode!=='host');$('#status').hidden=session.mode==='none';$('#exit-session').hidden=session.mode==='none';if(session.mode==='none')$('#phase-label').textContent=page==='invitation'?'活动入住':'体验导览';$('#navigation').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.action===page));let html='';
 if(page==='welcome')html=welcomeMarkup(person.ready);else if(page==='tour')html=tourMarkup(tourStep,sampleResident,person.ready);else if(page==='training')html=trainingMarkup();else if(page==='invitation')html=invitationMarkup(invitation,{busy:entering,error:entryError,ready:person.ready});else if(page==='invite-preview')html=invitationMarkup({valid:true,name:'森友小镇 · 协作体验活动'},{preview:true});else if(page==='avatar')html=avatar();else if(page==='questions')html=questionnaire();else if(page==='review')html=review();else if(page==='waiting')html=waiting();else if(page==='map')html=map();else if(page==='home')html=home();else if(page==='inbox')html=`<h2>森林来信</h2>${inbox()}${button('energy','去收取合作能量','green')}`;else if(page==='commons')html=commons();else if(page==='project')html=project();else if(page==='host')html=`${host()}<form id="town-name-form"><label for="town-name">本场合种林的名字</label><div class="row"><input id="town-name" name="name" maxlength="30" value="${esc(room.townName)}"><button type="submit">更新木牌</button></div></form>`;else if(page==='ceremony')html=ceremony();panel.innerHTML=html;
}
async function start(mode,code,activityName){if(entering)return;if(!worldReady)return toast('小镇还在载入，请稍等。');pendingMode=mode;entering=true;entryError='';if(mode==='guest')render();try{resetPreview();if(mode==='demo')session.demo(publicPerson());else if(mode==='host')await session.host(publicPerson(),false,activityName);else await session.join(code,publicPerson());dialog.close();if(mode==='host'){setPage('host');world.showTown();return;}if(person.ready&&!confirmedStory(person.profile)){setPage('review');world.showHome(publicPerson());toast('旧资料已保留。请先确认新整理的短介绍。');return;}if(person.ready){if(room.phase===0){if(mode==='demo')await send('phase',{phase:1});else return setPage('waiting');setPage('map');world.showTown();}else{setPage(room.phase===3?'ceremony':'map');world.showTown();}}else{setPage('avatar');world.showAvatar(person.appearance);}}catch(e){session.close();session.mode='none';room=null;entryError='暂时没有连上本场活动：'+e.message;toast(entryError);}finally{entering=false;render();}}
document.addEventListener('input',e=>{if(e.target.closest('#project-form'))e.target.closest('#project-form').dataset.dirty='true';if(e.target.id==='name'){person.name=e.target.value;save();}if(e.target.id==='body'){person.appearance.body=e.target.value;save();world.styleAvatar(person.appearance);}});
document.addEventListener('change',e=>{if(e.target.id==='body'){person.appearance.body=e.target.value;save();world.styleAvatar(person.appearance);}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;if(entering)return toast('正在连接活动，请稍候。');const a=b.dataset.action;try{
 if(a==='tour-start')showTour();
 else if(a==='tour-step')showTour(b.dataset.step);
 else if(a==='entry-home'){dialog.close();history.replaceState(null,'',location.pathname);invitation=readInvitation('');resetPreview();setPage('welcome');}
 else if(a==='training-info'){resetPreview();setPage('training');}
 else if(a==='preview-invitation'){resetPreview();setPage('invite-preview');}
 else if(a==='show-invite-qr')showInviteQR();
 else if(a==='download-invite'){download(new Blob([invitationQR(activityInvite())],{type:'image/svg+xml'}),'森友小镇-本场入住二维码.svg');toast('本场二维码已生成；活动期间请保持主持页面在线。');}
 else if(a==='start-demo')await start('demo');
 else if(a==='join-form')modal(`<h2>参加同事组织的活动</h2><p>扫描老师展示的二维码可以直接进入；也可以在这里填入老师发来的邀请码。</p><form id="join-form"><label for="room-code">16 位活动邀请码</label><input id="room-code" name="code" minlength="16" maxlength="16" pattern="[a-fA-F0-9]{16}" required autocomplete="off"><button class="primary" type="submit">找到我的活动</button></form>`);
 else if(a==='host-form')modal(`<h2>组织一场小镇活动</h2><p>创建后，先展示二维码邀请学员入住，再按现场节奏开放串门、共建与开张。不用先替自己完成问答。</p><form id="create-activity-form"><label for="activity-name">活动名称</label><input id="activity-name" name="name" maxlength="40" value="森友小镇开张日" required><div class="notice">活动期间需保持本页和网络在线。实时连接使用 PeerJS / WebRTC，正式培训前请用现场设备试连。不要在活动名称里填入机密信息。</div><button class="primary" type="submit">同意并创建活动</button></form>${localStorage.getItem('senyou-opening-host')?button('resume-host','恢复上次组织的活动','text-button'):''}`);
 else if(a==='leave-session'){if(session.mode==='host'&&b.dataset.confirmed!=='true'){modal(`<h2>离开本场小镇？</h2><p>实时连接将中断。场次记录仍保存在本机，之后可恢复。</p><div class="actions">${button('cancel-dialog','继续主持')}${button('leave-session','确认离开','primary','data-confirmed="true"')}</div>`);return;}dialog.close();session.close();session.mode='none';room=null;$('#exit-session').hidden=true;world.setLocalResident(null);world.setResidents([]);world.setProjects({});world.setEnergy(0);world.showTown();setStatus('已离开场次 · 个人资料仍保存在本机');$('#host-nav').hidden=true;$('#mail-count').textContent='';$('#phase-label').textContent='小镇开张日';setPage('welcome');}
 else if(a==='cancel-dialog')dialog.close();
 else if(a==='start-host')await start('host');
 else if(a==='resume-host'){await session.host(publicPerson(),true);dialog.close();setPage('host');world.showTown();}
 else if(a==='hair-style'){person.appearance.hairstyle=Number(b.dataset.value);save();world.styleAvatar(person.appearance);render();}
 else if(a==='color'){if(b.dataset.key==='houseColor')person.houseColor=b.dataset.value;else person.appearance[b.dataset.key]=b.dataset.value;save();world.styleAvatar(person.appearance);render();}
 else if(a==='begin-questions'){if(!person.name.trim())return toast('先留一个居民昵称吧。');questionIndex=Math.max(0,QUESTIONS.findIndex(q=>!Number.isInteger(person.answers[q.id])));setPage('questions');}
 else if(a==='answer'){person.answers[QUESTIONS[questionIndex].id]=Number(b.dataset.index);person.profile=null;person.ready=false;save();render();}
 else if(a==='question-prev'){if(questionIndex===0){setPage('avatar');world.showAvatar(person.appearance);}else{questionIndex--;render();}}
 else if(a==='question-next'){if(!Number.isInteger(person.answers[QUESTIONS[questionIndex].id]))return;if(questionIndex<23){questionIndex++;render();}else{person.profile=makeProfile(person.answers);save();setPage('review');world.showHome(publicPerson());}}
 else if(a==='home'){if(!person.ready){if(session.mode==='none')return toast('先选择体验或加入场次。');setPage('avatar');world.showAvatar(person.appearance);}else showHome(session.id);}
 else if(a==='edit-profile')setPage('review');
 else if(a==='edit-avatar'){setPage('avatar');world.showAvatar(person.appearance);}
 else if(a==='save-avatar'){save();if(await send('profile',publicPerson()))showHome(session.id);}
 else if(a==='map'){if(gate()){setPage('map');world.showTown();send('presence',{location:'街区'});}}
 else if(a==='visit')showHome(b.dataset.id);
 else if(a==='section'){section=b.dataset.id;render();}
 else if(a==='inbox'){if(gate())setPage('inbox');}
 else if(a==='reply')showHome(b.dataset.id,'mail');
 else if(a==='commons'){if(gate()){world.showTown();setPage(room.phase===3?'ceremony':'commons');}}
 else if(a==='host'){if(room&&['host','demo'].includes(session.mode))setPage('host');}
 else if(a==='phase'){const phase=Number(b.dataset.value);const unfinished=Object.values(room.residents).filter(r=>!r.ready&&(session.mode!=='host'||r.id!==session.id)).length;if(phase===1&&unfinished&&b.dataset.confirmed!=='true'){modal(`<h2>还有 ${unfinished} 位居民未完成入住</h2><p>现在开放后，未完成者仍可继续填写。是否继续？</p><div class="actions">${button('cancel-dialog','再等一会儿')}${button('phase','仍然开放','green','data-value="1" data-confirmed="true"')}</div>`);return;}if(b.dataset.confirmed==='true')dialog.close();if(phase===3&&!Object.values(room.projects).some(p=>p.submitted)){toast('先共同提交至少一个项目，再迎接开张。');return;}if(await send('phase',{phase})&&phase===3){setPage('ceremony');world.showTown();}}
 else if(a==='pair'||a==='support-offer'){const r=room.residents[b.dataset.id];if(gate()&&r?.ready)modal(pairMarkup(room.residents[session.id],r,a==='support-offer'));}
 else if(a==='energy'){if(gate()){world.showTown();world.focusGrove();setPage(room.phase===3?'ceremony':'commons');}}
 else if(a==='collect-energy'){b.disabled=true;if(await send('collect',{id:b.dataset.id})){toast('能量收好了，可以为合种林浇水。');render();}else b.disabled=false;}
 else if(a==='water'){b.disabled=true;world.showTown();world.focusGrove();if(await send('water',{})){toast('你的合作能量已经汇入合种林。');render();}else b.disabled=false;}
 else if(a==='accept'){await send('accept',{id:b.dataset.id});render();}
 else if(a==='simulate-accept'){session.simulateAccept(b.dataset.id);toast('已模拟对方确认。真实场次需要对方亲自操作。');render();}
 else if(a==='reload-project')render();
 else if(a==='approve-project'){if($('#project-form')?.dataset.dirty==='true')return toast('你还有未保存的修改，请先保存，再确认当前稿件。');if(await send('projectApprove',{id:b.dataset.id,baseRevision:Number(b.dataset.revision)})){toast('已确认当前讨论稿。');render();}}
 else if(a==='simulate-approval'){session.simulateApproval(b.dataset.id);toast('已模拟伙伴确认当前稿件。');render();}
 else if(a==='project-view'){activeProject=b.dataset.id;setPage('project');}
 else if(a==='project-join'){await send('projectJoin',{id:b.dataset.id});render();}
 else if(a==='simulate-project'){session.simulateProject(b.dataset.id);render();}
 else if(a==='copy-invite'||a==='copy-code'){await navigator.clipboard.writeText(a==='copy-code'?session.code:activityInvite());toast('已复制，可发给本场参与者。');}
 else if(a==='reconnect'){await session.join(session.code,publicPerson());toast('已重新连接。');}
 else if(a==='save-reflection'){person.reflection=$('#reflection').value.slice(0,1200);save();toast('今天的发现已保存在本机。');}
 else if(a==='download')await downloadCard();
 else if(a==='grove-memento')await downloadGrove();
 else if(a==='export-room'){const out={phase:PHASES[room.phase],groveName:room.townName,wateredEnergy:energy(room),projects:room.projects,participants:Object.values(room.residents).map(r=>({name:r.name,ready:r.ready,simulated:!!r.demo})),visits:room.visits.length};download(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),'小镇公共成果.json');}
 else if(a==='about')modal(`<h2>今天，一起把小镇开起来</h2><p>先认识自己，再走访邻居。找到伙伴后，在有限材料里共同完成一个公共项目，最后带走自己的居民卡和合作约定。</p><h3>体验的边界</h3><p>${DISCLAIMER}</p><p>所有经历和能力由本人填写。回答更多，只会让自我描述更丰富，不代表测评更准确。个人支持需求默认不分享。原始答题仅保存在本人浏览器。</p><p>真实场次使用主持人在线中枢和第三方 PeerJS 信令。居民之间只同步确认分享的资料，留言仅向双方显示；主持人作为中枢能够接触场次数据。请用昵称，不填敏感信息。清理本机数据可使用浏览器站点数据设置。</p><h3>来自蚂蚁森林的启发</h3><p>合种广场、共同浇灌的能量、梭梭与胡杨、物种观察和成长纪念。场景为原创 Blender 建模；本体验非蚂蚁森林官方产品，不产生真实绿色能量、碳减排或公益捐种。</p><ul class="small-list">${SOURCES.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener noreferrer">${t}</a></li>`).join('')}</ul>`);
}catch(error){toast(error.message);}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['profile-form','message-form','agreement-form','project-form','join-form','town-name-form','create-activity-form','invitation-form'].includes(f.id))return;e.preventDefault();const data=new FormData(f);try{
 if(f.id==='create-activity-form'){const submit=f.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='正在创建活动…';await start('host',null,String(data.get('name')||'').trim());if(dialog.open){submit.disabled=false;submit.textContent='重试创建活动';}return;}
 if(f.id==='invitation-form'){await start('guest',invitation.code);return;}
 if(f.id==='town-name-form'){if(await send('townName',{name:data.get('name')}))toast('本场木牌已更新。');return;}
 if(f.id==='join-form'){showInvitation(data.get('code'));return;}
 if(f.id==='profile-form'){const next=Object.fromEntries(fields.map(([k])=>[k,String(data.get(k)||'').trim()])),before=buildStory(person.profile),after=buildStory(next);if(before.basis!==after.basis){person.profile=next;person.shareSupport=data.get('shareSupport')==='on';save();render();toast('完整自述有修改，短介绍已重新整理。请检查后再次确认。');return;}next.story={...after,...Object.fromEntries(STORY_FIELDS.map(([k])=>[k,String(data.get('story-'+k)||'').trim()]))};person.profile=next;person.shareSupport=data.get('shareSupport')==='on';person.ready=true;save();if(!await send('profile',publicPerson()))return;if(session.mode==='demo'&&room.phase===0)await send('phase',{phase:1});if(room.phase===0)setPage('waiting');else showHome(session.id);toast('已确认。邻居将看到你认可的短介绍与便签。');}
 if(f.id==='message-form'&&await send('message',{to:f.dataset.to,body:data.get('body')})){f.reset();toast(session.mode==='demo'?'留言已保存在本机体验信箱。':'留言已由主持端确认，对方上线后也能看到。');render();}
 if(f.id==='agreement-form'){const text=f.dataset.kind==='support'?data.get('text'):`开始前，先说清 ${data.get('start')}\n中途碰进度 ${data.get('check')}\n遇到分歧，我们就 ${data.get('diff')}`;if(await send('agreement',{to:f.dataset.to,text,kind:f.dataset.kind})){dialog.close();setPage('inbox');toast('邀请已发出，等待对方确认。');}}
 if(f.id==='project-form'&&await send('projectSave',{id:activeProject,baseRevision:Number(f.dataset.revision),choices:data.getAll('choice').map(Number),text:data.get('text'),submit:e.submitter?.value==='submit'})){toast(e.submitter?.value==='submit'?'共同成果已提交。':'讨论稿已保存。');render();}
}catch(error){toast(error.message);}});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function downloadCard(){
 if(!person.ready)return toast('先确认你的档案。');
 const canvas=document.createElement('canvas');canvas.width=1000;
 const c=canvas.getContext('2d'),lines=[];let y=600;
 function layout(text,font=24,line=40,color='#30483b'){
  c.font=`${font}px sans-serif`;
  for(const paragraph of String(text||'').split('\n')){let s='';for(const ch of paragraph){if(c.measureText(s+ch).width>860){lines.push({text:s,y,font,color});s='';y+=line;}s+=ch;}lines.push({text:s,y,font,color});y+=line;}
 }
 const story=confirmedStory(person.profile);layout(story?.headline||person.profile.intro,28,44);const sections=story?[['关于我',story.about],['找我合作',story.invite],['讨论时',story.quiet],['有分歧时',story.talk],['我做过的事',person.profile.experience],['这次愿意参与',person.profile.offer],['下一次，我想试试',story.practice]]:[['我的做事习惯',person.profile.habits],['怎样和我沟通',person.profile.communication]];for(const [title,text] of sections){if(!text)continue;y+=28;layout(title,26,44,'#52745a');layout(text,22,36);}const myProjects=Object.values(room?.projects||{}).filter(p=>p.submitted&&p.members.includes(session.id));if(myProjects.length){y+=28;layout('我参与的公共项目',26,44,'#52745a');layout(myProjects.map(p=>PROJECTS.find(d=>d.id===p.id)?.name).join('、'),22,36);}
 if(person.reflection){y+=28;layout('今天的新发现',26,44,'#52745a');layout(person.reflection,22,36);}
 canvas.height=Math.max(1500,y+140);c.fillStyle='#f8f1e3';c.fillRect(0,0,1000,canvas.height);c.fillStyle='#52745a';c.fillRect(0,0,1000,20);
 try{const picture=new Image();picture.src=world.snapshot();await picture.decode();c.drawImage(picture,65,205,870,330);}catch{}
 c.fillStyle='#30483b';c.font='bold 48px sans-serif';c.fillText('森林居民卡',65,110);c.font='30px sans-serif';c.fillText(person.name,65,170);
 for(const l of lines){c.font=`${l.font}px sans-serif`;c.fillStyle=l.color;c.fillText(l.text,65,l.y);}
 c.fillStyle='#667366';c.font='18px sans-serif';c.fillText('本人确认的自我描述 · 非专业 DISC 结论 · 不含私人支持需求',65,canvas.height-70);c.fillText('蚂蚁森友小镇 · 小镇开张日',65,canvas.height-35);
 canvas.toBlob(blob=>{if(blob){download(blob,person.name+'-森林居民卡.png');toast('居民卡已生成，带走你的短介绍与合作发现。');}else toast('生成失败，请重试。');});
}
async function downloadGrove(){
 if(room?.phase!==3)return toast('开张后再一起留下纪念。');world.showTown();await new Promise(resolve=>setTimeout(resolve,1100));
 const canvas=document.createElement('canvas');canvas.width=1000;const c=canvas.getContext('2d'),lines=[];let y=640;
 const write=(text,size=25)=>{c.font=`${size}px sans-serif`;for(const paragraph of String(text).split('\n')){let line='';for(const ch of paragraph){if(c.measureText(line+ch).width>860){lines.push({text:line,y,size});y+=42;line='';}line+=ch;}lines.push({text:line,y,size});y+=42;}y+=20;};
 write('一起参与的居民',28);write(Object.values(room.residents).filter(r=>r.ready).map(r=>r.name+(r.demo?'（模拟）':'')).join(' · '));write('共同留下的成果',28);for(const p of Object.values(room.projects).filter(p=>p.submitted)){write(PROJECTS.find(d=>d.id===p.id).name,27);write(p.text,23);}canvas.height=y+150;c.fillStyle='#f8f1e3';c.fillRect(0,0,1000,canvas.height);c.fillStyle='#52745a';c.fillRect(0,0,1000,18);c.font='bold 38px sans-serif';c.fillText('合种纪念 · 小镇开张日',65,90);c.font='28px sans-serif';c.fillText(room.townName,65,145);c.font='20px sans-serif';c.fillText(new Date(room.createdAt).toLocaleDateString('zh-CN')+' · 已浇灌 '+energy(room)+' 份协作能量',65,190);const pic=new Image();pic.src=world.snapshot();await pic.decode();c.drawImage(pic,65,225,870,350);for(const l of lines){c.font=`${l.size}px sans-serif`;c.fillStyle='#30483b';c.fillText(l.text,65,l.y);}c.font='19px sans-serif';c.fillStyle='#667366';c.fillText('活动纪念 · 非官方植树证书 · 不产生真实捐种或碳减排',65,canvas.height-70);canvas.toBlob(blob=>{if(blob)download(blob,'森友小镇-本场合种纪念.png');});
}
render();try{world=new ForestWorld($('#world'),event=>{if(session.mode==='none'){if(event.type==='section'){const step=['door','archive','table'].indexOf(event.id);if(step>=0)showTour(step);else toast('正式活动中，信箱用来接收邻居留言和合作约定。');}else if(event.type==='resident')showTour(0);else if(['commons','energy'].includes(event.type))showTour(3);return;}if(event.type==='resident')showHome(event.id);else if(event.type==='section'){section=event.id;render();}else if(event.type==='commons'||event.type==='energy'){if(gate()){setPage(room.phase===3?'ceremony':'commons');world.focusGrove();}}else if(event.type==='species')modal('<h2>森林里的三位邻居</h2><p>这是一处科普微缩展区。梭梭、胡杨与花棒分别展示，不代表它们在同一块地里自然共生。</p><h3>梭梭 · 细枝伸向天空</h3><p>展台用疏朗的细枝表现梭梭，呼应蚂蚁森林早期在阿拉善的种植故事。</p><h3>胡杨 · 看看它的树冠</h3><p>用独立的树干与金绿色叶片展示胡杨的形态意象。</p><h3>花棒 · 沙地上的花色</h3><p>粉紫色的小花沿枝条点缀，让展区有不同于乔木的层次。</p><p class="muted">原创 Blender 示意模型，非植物识别或种植指导。物种不对应人的固定人格。</p>');});world.load().then(()=>{worldReady=true;$('#loading').hidden=true;window.__senyouReady=true;setStatus('先逛一逛 / 培训扫码入住');render();}).catch(error=>{$('#loading').innerHTML='小镇未能载入。请检查网络后刷新。';console.error(error);});}catch(error){$('#loading').textContent='当前设备无法显示 3D，请使用支持 WebGL 的浏览器。';console.error(error);}
window.addEventListener('beforeunload',e=>{if(session.mode==='host'&&session.links.size){e.preventDefault();e.returnValue='主持人离开将中断实时场次。';}});
window.addEventListener('pagehide',()=>session.close());
