import {confirmedStory,buildStory,STORY_FIELDS,archiveDetails,extraNotes,supportNote} from './opening-story.js?v=grove3';
import {wallet,growthState} from './opening-energy.js?v=grove3';
import {PROJECTS} from './opening-content.js?v=grove3';
export const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
const fold=(title,html,cls='')=>`<details class="paper-fold ${cls}"><summary>${e(title)}</summary>${html}</details>`;
const note=(title,text)=>`<article class="table-note"><h3>${e(title)}</h3><p>${e(text)}</p></article>`;
export function archiveMarkup(p,name,own){const s=confirmedStory(p);if(!s)return `<div class="archive-sheet"><h3>关于我的几件事</h3><p>${e((p.habits||'这部分暂未分享。').split('\n')[0])}</p>${fold('查看本人原有自述',`<p class="paper-text">${e(p.habits)}</p><p>${e(p.growth)}</p>${p.experience?`<h3>我做过的事</h3><p>${e(p.experience)}</p>`:''}`)}${own?'<p class="muted">你的旧资料都还在。点“修改档案”，确认新的短介绍。</p>':''}</div>`;
 return `<article class="archive-sheet"><div class="folder-tab">${e(name)}的几件小事</div><h3 class="story-headline">${e(s.headline)}</h3><p class="story-about">${e(s.about)}</p>${s.practice?`<div class="practice-note"><small>这次想试试</small><p>${e(s.practice)}</p></div>`:''}</article>${fold('再认识我一点',archiveDetails(p).map(x=>note(x.title,x.text)).join('')+(p.experience?note('我做过的事',p.experience):'')+fold('我确认过的完整自述',`<p class="paper-text">${e(p.habits)}</p>`))}${own&&!p.experience?'<button class="quiet small" data-action="edit-profile">添一件自己的小故事</button>':''}`;
}
export function tableMarkup(p,own,shareSupport,id){const s=confirmedStory(p);return `${s?`<p class="table-welcome">坐一会儿，咱们慢慢聊。</p><div class="table-notes">${note(s.inviteTitle,s.invite)}${note(s.quietTitle,s.quiet)}${note(s.talkTitle,s.talk)}</div>`:`<p>${e((p.communication||'这部分暂未分享。').split('\n')[0])}</p>`}${!own?`<div class="actions"><button class="green" data-action="pair" data-id="${e(id)}">从一句话聊起</button><button data-action="support-offer" data-id="${e(id)}">留下一份支持</button></div>`:'<p class="muted">这些便签会留给来访的邻居，也可以随时改成自己的话。</p>'}${fold('还有几件小事',extraNotes(p).map(x=>note(x.title,x.text)).join('')+fold('我确认过的完整自述',`<p class="paper-text">${e(p.communication)}</p>`))}${p.support?fold(own&&!shareSupport?'忙乱的时候 · 仅自己可见':'忙乱的时候，这样帮我就好',`<p class="support-copy">${e(supportNote(p))}</p><small>${own&&!shareSupport?'这张纸条不会发送给邻居。':'这张纸条由本人选择向本场居民分享。'}</small>`,'private-note'):''}`;}
export function storyEditor(p){const s=confirmedStory(p)||buildStory(p);return `<div class="notice">这像我吗？先看看下面的短介绍。你可以改写或清空任何非必填内容，确认后才会分享。</div><div class="story-editor">${STORY_FIELDS.map(([key,label,n])=>`<label for="s-${key}">${e(label)}</label><textarea id="s-${key}" name="story-${key}" maxlength="${n}" rows="2">${e(s[key])}</textarea>`).join('')}</div>`;}
export function pairMarkup(me,other,support=false){const s=confirmedStory(other.profile),q=s?.question||'这次一起做事，你最希望我先了解什么？';return `<h2>${e(me.name)} × ${e(other.name)}</h2><p class="chat-prompt">${support?'读过这些便签，你愿意提供哪一份具体的帮助？':e(q)}</p><p class="muted">先聊一聊，再把双方愿意尝试的办法记下来。对方确认前，这只是一份邀请。</p><form id="agreement-form" data-to="${e(other.id)}" data-kind="${support?'support':'cooperation'}">${support?'<label for="agreement">我愿意这样支持你</label><textarea id="agreement" name="text" required maxlength="400" placeholder="例如，下次讨论，我可以帮你把几个方案整理成一张比较表。"></textarea>':'<label for="agree-start">开始前，先说清</label><input id="agree-start" name="start" maxlength="100" required placeholder="例如，目标和完成标准"><label for="agree-check">中途什么时候碰一次进度</label><input id="agree-check" name="check" maxlength="100" required placeholder="一起约个时间或节点"><label for="agree-diff">遇到分歧，我们就</label><input id="agree-diff" name="diff" maxlength="100" required placeholder="写一个双方愿意尝试的办法">'}<div class="actions"><button type="submit" class="primary">请对方看看</button></div></form><p class="muted">同一对伙伴首次确认合作或支持，各获得 4 份协作能量。后续约定仍会保存，不重复奖励。</p>`;}
export function energyMarkup(room,id){const w=wallet(room,id),g=growthState(room);return `<section class="grove-progress"><div class="row spread"><small>合种木牌 · ${Object.values(room.residents).filter(r=>r.ready).length} 位居民</small><strong>${g.value} / ${g.target}</strong></div><h3>${e(room.townName)}</h3><p>${g.label}</p><div class="growth-track"><span style="width:${Math.round(g.progress*100)}%"></span></div><p class="muted">本场成长目标随真实入住人数调整。能量只记录协作，不代表绿色能量或真实捐种。</p></section><div class="energy-pouch"><div class="row spread"><h3>我的能量小袋</h3><span>${w.available} 份可浇灌</span></div>${w.pending?`<p>${w.pending} 份合作能量，等你收好。</p>`:'<p class="muted">共同确认约定或交付项目后，能量会出现在这里。</p>'}<div class="energy-list">${w.entries.filter(x=>!x.collected).map(x=>`<button class="energy-pick" data-action="collect-energy" data-id="${e(x.id)}"><span class="energy-dot">+${x.amount}</span><span>${x.kind==='project'?e(PROJECTS.find(p=>p.id===x.ref)?.name||'共建项目'):'一份双方确认的约定'}<small>点击收取</small></span></button>`).join('')}</div><button class="green water-button" data-action="water" ${w.available?'':'disabled'}>为合种林浇水${w.available?' · '+w.available+' 份':''}</button>${fold('看看能量的来处',`<p class="muted">一对伙伴首次确认，各获得 4 份；共同项目交付后，每位成员获得 10 份。浏览、串门和重复点击不加分。先收取，再浇水。</p><p class="muted">我已浇灌 ${w.watered} 份。${room.version===3?'旧场次已确认的合作与交付也可领取一次。':''}</p>`)}</div>`;}
