// Host-owned, one-time rewards. Visits and client-supplied amounts never mint energy.
const award=(room,owner,id,amount,kind,ref)=>{if(!room.ledger.some(e=>e.id===id))room.ledger.push({id,owner,amount,kind,ref,createdAt:Date.now(),collected:false,watered:false});};
export function awardAgreement(room,a){const pair=[a.from,a.to].sort().join(':');for(const owner of [a.from,a.to])award(room,owner,'pair:'+pair+':'+owner,4,'agreement',a.id);}
export function awardProject(room,p){for(const owner of p.members)award(room,owner,'project:'+p.id+':'+owner,10,'project',p.id);}
export function prepareEnergy(room){if(!Array.isArray(room.ledger)){room.ledger=[];for(const a of room.agreements||[])if(a.accepted)awardAgreement(room,a);for(const p of Object.values(room.projects||{}))if(p.submitted)awardProject(room,p);}room.version=3;room.townName||='我们的第一片合种林';return room;}
export const wateredEnergy=room=>room.publicEnergy??(room.ledger||[]).filter(e=>e.watered).reduce((s,e)=>s+e.amount,0);
export function wallet(room,id){const entries=(room.ledger||[]).filter(e=>e.owner===id);return {entries,pending:entries.filter(e=>!e.collected).reduce((s,e)=>s+e.amount,0),available:entries.filter(e=>e.collected&&!e.watered).reduce((s,e)=>s+e.amount,0),watered:entries.filter(e=>e.watered).reduce((s,e)=>s+e.amount,0)};}
export function energyAction(room,id,type,p){const entries=room.ledger.filter(e=>e.owner===id);if(type==='collect'){const e=entries.find(e=>e.id===p.id);if(!e)throw Error('这颗能量不属于你。');if(e.collected)throw Error('这颗能量已经收好，不会重复增加。');e.collected=true;}else{const available=entries.filter(e=>e.collected&&!e.watered);if(!available.length)throw Error('先收取一颗合作能量，再来浇水。');for(const e of available){e.watered=true;e.wateredAt=Date.now();}}}
export function growthState(room){const value=wateredEnergy(room),target=Math.max(20,Object.values(room.residents||{}).filter(r=>r.ready&&!r.demo).length*10),progress=Math.min(1,value/target);return {value,target,progress,label:value===0?'等待第一份浇灌':progress<.35?'小树正在抽枝':progress<1?'树冠慢慢展开':'我们的合种林长成了'};}
