import { cognition,sample,SAMPLES,DIMS,STYLES,WINDOWS,LIGHTS,BOOKS,QUESTIONS,recipe,mirrorFeedback,labComparison,labPrescription,PRESCRIPTIONS,progress,REACTIONS,mirrorQuestions } from './cognition-data.js?v=cognition-v1';
import { joined } from './villages.js?v=cognition-v1';

export function createCognitionUI(ctx){
 const {getState:s,getWorld:w,getHomeId,commit,panel,button,esc,toast,close,hud,walkHome}=ctx,$=q=>document.querySelector(q);
 const c=()=>cognition(s()),r=()=>s().residents.find(x=>x.id===s().actor);
 const b=(t,a,d='',cls='')=>button(t,'cog-'+a,d,cls);
 const check=(id,label,value=false)=>`<label class="checkline"><input id="${id}" type="checkbox" ${value?'checked':''}>${label}</label>`;
 const field=(id,label,value='',placeholder='',rows=3)=>`<label class="field">${label}<textarea id="${id}" rows="${rows}" maxlength="400" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;
 const values=sel=>[...document.querySelectorAll(sel)].map(x=>Number(x.value));
 const privateHere=()=>w()?.mode==='home'&&getHomeId()===s().actor&&w().studyOpen;
 let selectedBook=0,publicationSource='door',exportURL=null,exportBlob=null,exportFingerprint=null,pendingPartner=null;
 function dispose(){if(exportURL)URL.revokeObjectURL(exportURL);exportURL=exportBlob=exportFingerprint=null;}
 function show(title,body,foot='',cls='') {panel(title,'私人认知区 · 仅本人可见 · 虚构报告演示',body,foot||b('收好，继续在屋里探索','close'),'cognition-panel '+cls);}
 const bars=v=>`<div class="cog-bars">${DIMS.map((d,i)=>`<div><span>${d}</span><meter min="0" max="100" value="${v[i]}">${v[i]}</meter><small>${v[i]}</small></div>`).join('')}</div>`;
 function missing(){show('先认识这份示例的来源','<p>报告匣放在私人区的右下角。先走过去，主动选择一份明确标注的虚构报告，再回来探索。没有报告时，不为你猜测画像。</p>',b('走到报告匣旁','walk','data-key="cog-report"','primary'));}
 function report(){
  const current=sample(s());show('打开我的报告匣',`<p>这里演示“已有报告进入小屋”的过程，不重新测评，也不解析真实员工文件。请勿输入真实报告原文。</p><label class="field">选择一份虚构报告<select id="cog-report-id">${Object.values(SAMPLES).map(x=>`<option value="${x.id}" ${current?.id===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label>${check('cog-report-consent','我知道这是一份虚构示例，不是我的真实测评。')}${current?`${check('cog-report-replace','如更换示例，同意重置私人探索；已公开的本人介绍不会被自动改写。')}<h3>${esc(current.title)}</h3><p>${esc(current.summary)}</p><div class="cog-report-states">${WINDOWS.map(([key,name])=>`<section><h4>${name}</h4>${bars(current[key])}</section>`).join('')}</div><h3>协作与激励提示</h3><p>${esc(current.meeting)}</p><p>${esc(current.strength)}；可以练习：${esc(current.practice)}</p><p>${LIGHTS.map((x,i)=>`${x[1]}：${['暂不需要','少量','重要','很重要'][current.lights[i]]}`).join(' · ')}</p><small>四维数值是样例的视觉输入，不表示能力、优劣或关系成功率。原始样例保持不变，后续校准单独保存。</small>`:'<p class="notice">还未载入报告。入驻和公开个人介绍不以载入报告为前提。</p>'}`,b(current?'保存选择并收好报告':'载入示例并收好报告','report-save','','primary'));
 }
 function exterior(){show('我的小屋，不只有一种样子',`<p>报告提供一个起点，你决定哪些元素像自己。当前最突出的元素是“${STYLES[c().mix.indexOf(Math.max(...c().mix))][1]}”，其余元素仍然保留。这是四维“灰度光谱”：四种倾向可以共存，不必合计为100%。调整的是外观表达，不改原始报告。</p><div class="cog-style-controls">${STYLES.map(([dim,title,hint],i)=>`<label><strong>${title}</strong><span>${hint}</span><input data-cog-mix type="range" min="0" max="100" value="${c().mix[i]}" aria-label="${title}像我的程度"><output>${c().mix[i]}</output></label>`).join('')}</div><p>瞭望装置、交流桌、陪伴绿植和工艺台会随配方调整。保存后出门看实际小屋，私人报告不因此对外公开。</p>`,b('保存外观配方','mix-save','','primary')+b('保存并出门看小屋','mix-out'));
 }
 function windowView(id,confirmed=false){
  if(id==='pressure'&&!c().stormUnlocked&&!confirmed){show('风暴窗前，先停一停','<p>压力下的反应不等于“真实的你”，也不代表能力不足。这里会出现柔和雨色，不会突然制造恐怖或压迫画面。</p><p>你可以暂时离开，也可以主动推窗，把描述与你的具体经历对照。</p>',b('我愿意，推开风暴窗','storm-open','','primary')+b('暂时不看','close'));return;}
  if(!commit({type:'cog:window',id,confirmed:id==='pressure'}))return;
  const item=WINDOWS.find(x=>x[0]===id),p=sample(s());show(item[1],`<div class="cog-window-landscape ${id}"><span>${id==='natural'?'晨光落在树梢':id==='work'?'市集里的工作节奏':'风雨经过，不定义你'}</span></div><h3>${item[2]}</h3>${bars(p[id])}<p>${id==='natural'?p.summary:id==='work'?'工作状态是面对要求时的适应。与晨光窗比较，看看哪些倾向加强了，哪些暂时收了起来。':'先看变化，再想想触发它的具体条件。压力书已经可以由你主动阅读。'}</p>${field('cog-window-note','这让我想起哪一次经历？',c().windowNotes[id]||'','只记在私人区，不放进公开介绍。')}<small>三状态是同一个人的不同情境，不是三个固定人格。示例数值不用于判断健康或能力。</small>`,b('保存这一扇窗的发现','window-save',`data-id="${id}"`,'primary')+b('收好，走向另一扇窗','close'));
 }
 function shelf(){show('16本书，16个认识自己的线索',`<p>正面精装是常用优势，侧放是次要倾向，斜放是需要留意的一面；压力书在本人打开风暴窗后解锁。不需要把每个词都认领。</p><div class="cog-bookcase">${BOOKS.map((book,i)=>b(book.title+(c().bookMarks[book.id]?' ✓':''),'book',`data-index="${i}" ${book.kind==='pressure'&&!c().stormUnlocked?'disabled':''}`,`cog-book ${book.kind}`)).join('')}</div><p>${Object.keys(c().bookMarks).length}/16 本已留下校准 · 可直接点击场景中的每一本书。</p>`,b('收好，继续探索','close'));}
 function book(index){selectedBook=Number(index);const book=BOOKS[selectedBook];if(!book)return;const mark=c().bookMarks[book.id];if(book.kind==='pressure'&&!c().stormUnlocked){toast('这本压力书先留在玻璃柜里。由你主动推开风暴窗后再读。');return;}
  show(`翻开《${book.title}》`,`<div class="cog-open-book"><p>${esc(book.text)}</p><small>${({core:'常用优势',secondary:'次要倾向',shadow:'需要留意的一面',pressure:'压力下的倾向'})[book.kind]} · 示例描述，不是对你的定论</small></div><label class="field">这像我吗？<select id="cog-book-match">${[['yes','很像我'],['part','部分像，看情境'],['no','不太像我']].map(([v,t])=>`<option value="${v}" ${mark?.match===v?'selected':''}>${t}</option>`).join('')}</select></label>${field('cog-book-note','留一个具体例子',mark?.example||'','可以写符合的经历，也可以说明哪里不符合。')}${book.kind==='shadow'?check('cog-book-turn','把这本书摆正：我愿意看见这一面，不等于认同标签。',mark?.turned):''}`,b('保存校准并放回书架','book-save','','primary')+b('回看整座书架','shelf'));
 }
 function door(){show('门牌的里面与外面',`<p>门牌里面留给自己；外面只带出你愿意告诉同事的一句话。这里先保存私人草稿，随后走到分享出口亲自确认。</p>${field('cog-door-strength','内面 · 我愿意用好的优势',c().door.strength)}${field('cog-door-practice','内面 · 我想练习的一小步',c().door.practice)}${field('cog-door-suggestion','外面 · 可以怎样和我配合',c().door.suggestion)}<p class="notice">当前公开门牌：${esc(r().public.collaboration?r().profile.collaboration:'这句协作介绍尚未公开。')}</p>`,b('保存双面门牌草稿','door-save','','primary')+b('走到分享出口再确认','walk','data-key="cog-share"'));
 }
 function mirror(){show('在壁炉镜子前，慢慢回看一次经历',`<p>三道示例面谈问题随你载入的报告调整。先写具体发生过的事，再决定报告描述有多像你。回答和分数始终私密。可以明确写“暂不回答”。</p>${mirrorQuestions(s()).map((q,i)=>field('cog-mirror-'+i,q,c().mirror.answers[i])).join('')}<label class="field">这段示例画像与我的经历有多贴近？<input id="cog-rating" type="range" min="1" max="10" value="${c().mirror.rating}"><output>${c().mirror.rating}/10</output></label><small>这是本人自报的贴近程度，不是系统测量的认知准确率。</small>${field('cog-mirror-line','给下次的自己留一句话',c().mirror.reflection,'例如：着急之前，先问对方卡在哪里。')}${c().seen.mirror?`<div class="cog-feedback"><h3>镜子里的回应</h3><p>${esc(mirrorFeedback(s()))}</p></div>`:''}`,b('保存反思，看看镜子回应','mirror-save','','primary')+b('收好，继续探索','close'));
 }
 function sun(){show('什么光，会让我更容易发挥？',`<p>走过四束光，看看不同支持对你的意义。关一束光只是情境模拟，不表示你缺少某种能力；屋里仍保留舒适的基础照明。</p><div class="cog-light-list">${LIGHTS.map(([id,title,hint,missing],i)=>`<section><h3>${title}</h3><p>${hint}</p><label class="field">我现在需要多少？<select data-cog-need="${id}">${[0,1,2,3].map(n=>`<option value="${n}" ${c().lightNeeds[i]===n?'selected':''}>${['暂不需要','少量就好','很重要','特别重要'][n]}</option>`).join('')}</select></label>${b(c().lightOn[i]?'关掉这束光，试试看':'重新点亮','light-toggle',`data-id="${id}"`)}${!c().lightOn[i]?`<p class="cog-feedback">缺光情境：${missing}</p>`:''}</section>`).join('')}</div><h3>我的光源配方</h3><p>${esc(recipe(s()))}</p><small>由本人选择的需要程度整理，不从行为猜测激励因素。</small>`,b('收好配方，继续探索','close')+b('走到分享出口选择一句','walk','data-key="cog-share"','primary'));
 }
 function sharing(source='door') {publicationSource=source;const line=source==='sun'?recipe(s()):source==='mirror'?c().mirror.reflection:c().door.suggestion;
  show('只带一句愿意分享的话出去',`<p>原始报告、四维分数、压力回答和自评留在屋内。这句话会替换当前协作介绍；先检查，再亲自确认。其他村的公开开关不变。</p><div class="actions">${b('门牌建议','share-source','data-source="door"',source==='door'?'primary':'')}${b('光源配方','share-source','data-source="sun"',source==='sun'?'primary':'')}${b('反思结论','share-source','data-source="mirror"',source==='mirror'?'primary':'')}</div>${field('cog-share-line','我愿意带出去的一句话',line,'先写一句自己确认的表达。')}${check('cog-share-confirm','我确认这句话代表我愿意表达的自己。')}${check('cog-share-public',`在${esc(s().village.name)}公开这句协作介绍`,!!r().public.collaboration)}<p class="notice">发布后，公开门牌、会客桌、懂我卡与《小屋里的我》读取同一句协作介绍。取消公开时，访客和分享图均不展示。</p>`,b('确认，带到我的协作介绍','publish','','primary')+b('先不带出去','close'));
 }
 function lab(){const l=c().lab,rows=s().residents.filter(x=>x.id!==s().actor&&x.confirmed&&x.membership==='joined');
  if(!l){show('合拍实验室 · 先选一位伙伴',`<p>这里探索“我们可能怎样配合”，不代表对方已经接受邀请。读取对方报告需要单独授权，不因串门获得权限。</p><label class="field">选择同村伙伴<select id="cog-partner">${rows.map(x=>`<option value="${x.id}" ${pendingPartner===x.id?'selected':''}>${esc(x.name)}${x.simulated?'（虚构居民）':''}</option>`).join('')}</select></label>${check('cog-partner-sample','本轮使用虚构居民已授权的示例报告；不代表真人授权。')}<p>本人的完整报告不公开。是否允许别人使用本村的报告样例比较，也由你另外选择。</p>${check('cog-lab-consent','允许本村伙伴在示例实验中对照我的报告样例',!!r().cognitionConsent)}${b('保存本村实验授权选择','lab-consent')}<small>未开放串门或没有合适伙伴时，先回森林认识邻居。</small>`,b('确认来源，开始成分对照','lab-start','','primary'));
  }else if(l.step===1){const d=labComparison(s());show('第一步 · 成分对照',`<p>一位是你载入的虚构报告，一位是${esc(s().residents.find(x=>x.id===l.partner)?.name)}的${l.simulated?'授权示例':'本村授权样例'}。只是探索起点，不是关系预测。</p><div class="cog-reagents"><section><h3>我的样例配方</h3>${bars(d.a.natural)}</section><section><h3>伙伴的样例配方</h3>${bars(d.b.natural)}</section></div><p class="quote">最大差异在 ${d.max===0?'推动与决断':d.max===1?'交流与表达':d.max===2?'稳定与节奏':'信息与标准'}。对方的不同不一定针对你，先问问他的条件。</p>`,b('让两份配方进入反应皿','lab-step','data-step="2"','primary')+b('重新选择伙伴','lab-reset'));
  }else if(l.step===2){const d=labComparison(s());show('第二步 · 看看混合反应',`<div class="cog-reaction"><span class="cog-vial"></span><span class="cog-vial second"></span><div class="cog-dish"><i></i><i></i><i></i></div></div><p>反应皿可以呈现五种反应。当前对照是规则示例，不是经验证的兼容性诊断。</p>${d.dimensions.map(x=>`<div class="cog-reaction-row"><strong>${x.dim}</strong><span>${x.type}</span><small>${x.type==='延迟冒泡'?'日常与压力状态可能不同，需要询问触发条件。':x.type==='气泡反应'?'看似相近，工作要求下可能有不同在意点。':x.type==='无反应'?'本项没有突出线索，不代表不适合。':x.type==='共振反应'?'有相近起点，仍要确认具体条件。':'差异可能成为分工线索，仍需实际商量。'}</small></div>`).join('')}<h3>五种反应图鉴 · 主动试试看</h3><p>点击后改变场景中的反应皿。这是单独的视觉图鉴，不改写两人的对照结果。</p><div class="actions">${REACTIONS.map(([id,title])=>b(title,'lab-focus',`data-id="${id}"`,l.focus===id?'primary':'')).join('')}</div>${l.focus?`<p class="cog-feedback">图鉴正在演示：${REACTIONS.find(x=>x[0]===l.focus)[1]}。${REACTIONS.find(x=>x[0]===l.focus)[2]}</p>`:''}`,b('留下一个可以尝试的协作处方','lab-step','data-step="3"','primary'));
  }else {const p=labPrescription(s());show('第三步 · 给下一次协作一张处方签',`<p>“处方”是游戏里的协作比喻，不是医学诊断，也不承诺次数达到就改善关系。</p><label class="field">这次想尝试什么<select id="cog-prescription">${PRESCRIPTIONS.map(x=>`<option value="${x[0]}" ${l.prescription===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><div class="cog-prescription"><p>本轮协作线索：两份虚构配方在 ${DIMS[labComparison(s()).max]} 上差异最明显。先把需要说清，不把差异当成冲突的定论。</p><h2>${p[1]}</h2><p>${p[2]}</p><h3>具体怎么用</h3><p>${p[3]}</p></div><h3>五次实践记录 · ${l.checks.length}/5</h3><ol>${l.checks.map(x=>`<li>${esc(x.text)} · ${({helpful:'这次有帮助',adjust:'还要调整','not-yet':'尚未尝试'})[x.outcome]}</li>`).join('')}</ol>${field('cog-practice','这次具体发生了什么？','','也可以如实写还没试，以及为什么。')}<label class="field">这次的感受<select id="cog-outcome"><option value="adjust">还要调整</option><option value="helpful">这次有帮助</option><option value="not-yet">尚未尝试</option></select></label><small>记录私密、单方自报，不替伙伴确认；气泡的视觉随回顾收拢，不代表真实关系治愈。</small>`,b('保存这一次实践','lab-check',l.checks.length>=5?'disabled':'','primary')+b('制作一张协作处方分享图','lab-export')+b('重新选择伙伴','lab-reset'));}
 }
 async function exportCard(){dispose();const p=labPrescription(s());if(!p)return;const line=r().public.collaboration?r().profile.collaboration:'';const snapshot=JSON.stringify([s().actor,c().lab,line]);exportFingerprint=snapshot;
  const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1440;const x=canvas.getContext('2d');x.fillStyle='#fff8ed';x.fillRect(0,0,1080,1440);x.fillStyle='#829475';x.fillRect(0,0,1080,18);
  const write=(v,y,size,max=4)=>{x.fillStyle='#355447';x.font=`${size}px "PingFang SC",sans-serif`;const lines=[''];for(const ch of v){if(x.measureText(lines.at(-1)+ch).width>880||ch==='\n')lines.push(ch==='\n'?'':ch);else lines[lines.length-1]+=ch;}lines.slice(0,max).forEach((t,i)=>x.fillText(t+(i===max-1&&lines.length>max?'…':''),90,y+i*(size+20)));};
  write('蚂蚁森友会 · 协作处方签',110,28);write(p[1],215,56);write(p[2],340,32);write('下次试着这样配合',570,28);write(p[3],640,30);if(line){write('我愿意公开的小提醒',865,26);write(line,930,28,3);}write('示例实验 · 不是人格诊断或效果承诺',1270,24);write('私人报告、反思与自评没有进入这张图',1330,24);
  exportBlob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!exportBlob)return;exportURL=URL.createObjectURL(exportBlob);
  show('协作处方签 · 先看，再决定分享',`<a href="${exportURL}" target="_blank" rel="noopener"><img class="cog-export" src="${exportURL}" alt="协作处方分享图，不含原始报告"></a>${check('cog-export-consent','我看过图片，愿意把这份个人协作尝试分享出去。')}<p>不显示伙伴名字、四维成分或私人记录，单方分享不冒充双方共识。</p>`,b('下载 PNG','download','','primary')+b('手机系统分享','native')+b('回实验台','lab'));
 }
 async function handle(a,d){if(!a.startsWith('cog-'))return false;
  const key=a.slice(4);if(key==='enter'){if(getHomeId()!==s().actor){toast('私人区只供主人使用。');return true;}close();w().enterStudy();hud();return true;}
  if(key==='visit-lab'){pendingPartner=d.id||null;close();walkHome(s().actor,()=>{w().enterStudy();hud();w().approach('cog-lab');});return true;}
  if(!privateHere()){toast('先回自己的小屋，走到屏风旁进入私人认知区。');return true;}
  if(key==='return'){close();w().leaveStudy();hud();return true;}if(key==='close'){close();hud();return true;}
  if(key==='walk'){close();w().approach(d.key);return true;}
  if(key==='report'){report();return true;}if(key==='report-save'){if(commit({type:'cog:report',id:$('#cog-report-id').value,confirmed:$('#cog-report-consent').checked,replace:!!$('#cog-report-replace')?.checked})){close();hud();toast('报告已收好。先走到入口旁的小屋风格配方，看看四种倾向。');}return true;}
  if(!c()){missing();return true;}
  if(key==='exterior')exterior();else if(key==='mix-save'||key==='mix-out'){if(commit({type:'cog:mix',values:values('[data-cog-mix]')})){close();hud();if(key==='mix-out'){w().leaveStudy();const pin=w().pins.find(x=>x.key==='exit');w().interact(pin);}else toast('外观配方已保存。出门能看见变化；接下来走向三扇窗。');}}
  else if(key.startsWith('window-')&&key!=='window-save')windowView(key.slice(7));
  else if(key==='storm-open')windowView('pressure',true);
  else if(key==='window-save'){if(commit({type:'cog:window-note',id:d.id,text:$('#cog-window-note').value})){close();hud();}}
  else if(key==='shelf')shelf();else if(key.startsWith('book-')&&/^book-\d+$/.test(key))book(key.slice(5));else if(key==='book')book(d.index);
  else if(key==='book-save'){if(commit({type:'cog:book',id:BOOKS[selectedBook].id,match:$('#cog-book-match').value,text:$('#cog-book-note').value,turned:!!$('#cog-book-turn')?.checked})){close();hud();}}
  else if(key==='door')door();else if(key==='door-save'){if(commit({type:'cog:door',strength:$('#cog-door-strength').value,practice:$('#cog-door-practice').value,suggestion:$('#cog-door-suggestion').value})){close();hud();}}
  else if(key==='mirror')mirror();else if(key==='mirror-save'){if(commit({type:'cog:mirror',answers:[0,1,2].map(i=>$('#cog-mirror-'+i).value),rating:$('#cog-rating').value,reflection:$('#cog-mirror-line').value}))mirror();}
  else if(key.startsWith('sun-')){sun();const id=key.slice(4);document.querySelector(`[data-cog-need="${id}"]`)?.closest('section')?.scrollIntoView({block:'center'});}
  else if(key==='sun')sun();else if(key==='light-toggle'){const i=LIGHTS.findIndex(x=>x[0]===d.id);if(commit({type:'cog:light',id:d.id,on:!c().lightOn[i]}))sun();}
  else if(key==='share')sharing();else if(key==='share-source')sharing(d.source);else if(key==='publish'){if(commit({type:'cog:publish',text:$('#cog-share-line').value,confirmed:$('#cog-share-confirm').checked,public:$('#cog-share-public').checked,source:publicationSource})){close();hud();toast('只带出了这一句话。公开与否按你刚才的选择，其他私人内容留在屋里。');}}
  else if(key==='lab')lab();else if(key==='lab-consent'){if(commit({type:'cog:consent',value:$('#cog-lab-consent').checked}))toast('只更新了本村实验授权。');}
  else if(key==='lab-start'){if(commit({type:'cog:lab-start',partner:$('#cog-partner')?.value,sampleConsent:$('#cog-partner-sample').checked}))lab();}
  else if(key==='lab-focus'){if(commit({type:'cog:lab-focus',id:d.id,illustration:true}))lab();}
  else if(key==='lab-step'){if(commit({type:'cog:lab-step',step:d.step}))lab();}
  else if(key==='lab-reset'){if(commit({type:'cog:lab-reset'}))lab();}
  else if(key==='lab-check'){if(commit({type:'cog:lab-check',text:$('#cog-practice').value,outcome:$('#cog-outcome').value}))lab();}
  else if(key==='lab-export')await exportCard();
  else if(key==='download'||key==='native'){
   if(!exportBlob||!$('#cog-export-consent')?.checked){toast('请先查看图片并确认愿意分享。');return true;}
   if(exportFingerprint!==JSON.stringify([s().actor,c().lab,r().public.collaboration?r().profile.collaboration:''])){toast('内容变化，请重新生成图片。');return true;}
   const file=new File([exportBlob],'森友会-协作处方.png',{type:'image/png'});if(key==='native'&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'我的协作处方'});}catch(e){if(e.name!=='AbortError')toast('可以点开原图长按保存。');}}else{const a=document.createElement('a');a.href=exportURL;a.download=file.name;a.click();if(key==='native')toast('当前浏览器不支持系统分享，已提供 PNG 下载；也可点开原图长按保存。');}
  }return true;
 }
 document.addEventListener('input',e=>{if(!privateHere())return;const el=e.target;if(el.matches('[data-cog-mix]')||el.id==='cog-rating')el.nextElementSibling.textContent=el.value+(el.id==='cog-rating'?'/10':'');});
 document.addEventListener('change',e=>{if(!privateHere())return;const el=e.target;if(el.dataset.cogNeed&&commit({type:'cog:light',id:el.dataset.cogNeed,need:el.value}))sun();if(el.id==='cog-prescription'&&commit({type:'cog:lab-prescription',id:el.value}))lab();});
 return {handle,dispose,door,progress:()=>progress(s())};
}
